### ISSUE TITLE
IC2 crashes game

### ISSUE THREAD

**Issue by TheK0tYaRa** [cabaletta/baritone#1083]
## Some information
Operating system: Windows 10 Pro x64
Java version: build 1.8.0_221_b11
Minecraft version: 1.12.2
Baritone version: 1.2.2
Forge mods (if used): IndustrialCraft2

## Exception, error or logs
https://paste.dimdev.org/ijevuhivuf.rb

## How to reproduce
1) Place isolated copper cable (theoretically any non-block)
2) Walk on it when it's connected
3) Crash

**Comment by ZeroMemes** [comment]
This issue could potentially arise in future Vanilla versions where we don't account for usage of the `isPassable` parameters being used, might as well just fix it.

**Comment by ZeroMemes** [comment]
Okay so I asked @leijurv for his feedback on this, and he noted that in order to handle this in the manner that the game intends, it would require the creation of a `BlockPos` object, this has been intentionally avoided during path calculation to minimize the performance cost of object creation.

I'll need to evaluate whether this issue is worth addressing.

**Comment by ZeroMemes** [comment]
Should be fixed by #1087, just has to be merged

**Comment by TheK0tYaRa** [comment]
Finally managed to compile it because i for some reason had 2 versions of java 8, gonna test it now

**Comment by TheK0tYaRa** [comment]
It still hates non-blocks, but at least it doesn't go straight to the crash town and continues working fine. But still gotta test it on the friend's server when it gets back up because i discovered the issue there.
