### ISSUE TITLE
Not moving

### ISSUE THREAD

**Issue by Haxorzz** [cabaletta/baritone#1143]
I dont know what caused it but while baritone was moving to the goal, it jumped into the water and did 1 block circles in the ocean, when I broke every block around it, then it began moving again, so weird

Update: Falling in water might cause it to glitch out, it's as if it want to land perfectly and goes back and forth whil ein the water, placing block to help it unblocked it

**Comment by DinoDinosaur** [comment]
Still happening. Windows 10, playing 1.15.2.
If you set the bot to explore and walk away for a while you've got a good chance of coming back to find it bobbing in water and unable to go forward. I installed and played with it today and it got stuck four times in about an hour and a half. I have the impression it only happens when the bot drops 2 or more blocks into the water, but I have not been able to confirm that.

**Comment by dominikaaaa** [comment]
See #1483

**Comment by BrainStone** [comment]
I mean this could (and should) be fixed regardless of if 1.13 swimming support is implemented as that causes the pathfinder to get stuck when dropping into water.
