### ISSUE TITLE
#sel terrain

### ISSUE THREAD

**Issue by TexRexTex** [cabaletta/baritone#1153]
## Describe your suggestion
`#sel terrain restore`
Would get the seed and restore the selection to what it was before user interference.

`#sel terrain fix`
Would adjust the selection to look like regular terrain.

`#sel terrain adjust`
would have options like dent, raise, and other things to adjust the terrain to your liking

## Settings
Restore option.
fix option.
adjust option.

## Context
this would greatly help if you were trying to revert explosion damage, make an island, or anything terrain-related.

## Final checklist
-  I have not used any OwO's or UwU's in this issue.

**Comment by Colmonkey** [comment]
This sounds alot like worldedit's naturalize command. It would be nice if baritone had this in order to do this in survival. Also, you could add a similar option to worldedit's smooth command. Its a very useful way to smooth out cliffs into hills, but again you can only do it in creative in worldedit, so baritone having a way to automate it in survival would be very nice.

**Comment by l1ving** [comment]
Seed crackers are out of scope.

**Comment by TexRexTex** [comment]
it would just use minecraft terrain gen to figure out what it looks like or you could enter the seed if you knew it to get the original terrain.

**Comment by l1ving** [comment]
That's what a seed cracker does, yes.
