### ISSUE TITLE
My baritone keeps getting stuck while building

### ISSUE THREAD

**Issue by Fogwin** [cabaletta/baritone#1194]
https://gyazo.com/71c5556a2f756343b02446b9cdb2d4de

**Comment by ThebesAndSound** [comment]
thats because you are scaffolding with blocks inside the build area. you can design your builds to use #buildinlayers without the need to make scaffold. also a new setting is coming soon to let you ignore blocks inside the build area, for your dirt scaffold above you would do '#buildignoreblocks dirt' before building

**Comment by Fogwin** [comment]
ok cool, But i have buildinglayers set to true, and scoffolding turned off. Maybe its just my schematic.

**Comment by AppleGUY2812** [comment]
hi
