### ISSUE TITLE
Baritone doesn't jump in water

### ISSUE THREAD

**Issue by SuperGamingBros4** [cabaletta/baritone#1271]
Baritone does not jump into water. I have searched through the settings for hours but can't find this feature. Could somebody help me.

**Comment by BongEatBong** [comment]
Could you provide more details about what you're trying to achieve? If you simply mean Baritone isn't taking a route through water/jumping into water during pathing, that's not necessarily incorrect behavior. Generally speaking Baritone takes the most efficient path to a destination. Just because you want it to path in water doesn't mean it makes the most sense from a pathing perspective.

Could you please provide more details?

**Comment by Xifong** [comment]
I think he is looking for baritone to take a running jump (into the water) whenever its path involves crossing water. At the moment, unless there is a parkour block placement into the water, Baritone will simply walk into it and then swim the whole distance; this is not just quite time consuming but also a bit suspicious since players generally avoid swimming as much as possible.

**Comment by Xifong** [comment]
Maybe I'm missing it but at the moment, I'm not sure where the extra time cost of water movement is factored in, as the classes in api.pathing.goals would be where I'd expect for this to happen. If this was the case, perhaps the issue would be fixed, but maybe right now Baritone doesn't consider parkour jumps which aren't specifically for crossing gaps.

**Comment by Xifong** [comment]
Oh actually, I'm seeing main.pathing.AStarPathFinder to be adding in the ActionCosts from MutableMoveResults, so it's probably just that this kind of jump is not currently being considered.

**Comment by leijurv** [comment]
Here's what you're looking for https://github.com/cabaletta/baritone/blob/master/src/main/java/baritone/pathing/movement/movements/MovementParkour.java#L77

**Comment by Xifong** [comment]
Ah I see (for now) ;)

**Comment by Xifong** [comment]
And thanks for pointing that out, there's a lot of code to get familiar with.

**Comment by SuperGamingBros4** [comment]
I found out that the issue was having the jesus hack on. And I have been having some issues with the execution of the path it makes. For example it jumps into water then trying to move it gets stuck trying to raise out of the water. (also sorry I forgot about this post I made)

**Comment by dominikaaaa** [comment]
Why are you commenting on some random unrelated issue? Enable `assumeWalkOnWater` if you want to use Jesus with baritone. 

This issue should've been closed as resolved already.
