### ISSUE TITLE
Can I only see the diamonds but not move automatically to them?

### ISSUE THREAD

**Issue by c4pp13** [cabaletta/baritone#1291]
(Hey, Im sorry if my english is too bad. I can't find if theres actually a command for this, but, here we go:)

Can I only activate to see the diamond (or other blocks) but not move to them? Like, some command as "see diamond_ore" but instead of going automatically to the diamond, I only see the green things showing where they are so I can go on my own. It would be great to disable the automine so I wont get caught in some servers...

**Comment by BongEatBong** [comment]
What I think you really want is the Search module from Impact client (which includes Baritone).

**Comment by S-B99** [comment]
there's a legit option for mine

**Comment by c4pp13** [comment]
> What I think you really want is the Search module from Impact client (which includes Baritone).

Im sorry to bother, but can you tell me how to do that?

**Comment by BongEatBong** [comment]
> Im sorry to bother, but can you tell me how to do that?

This is the incorrect place to ask for assistance with Impact (correct place would be Impact Discord server in #help) but since you've already asked, might as well answer. 

You can access a Search GUI to add/remove blocks through the ESC menu. Other than that, you can also use command .search add/remove [block_name]. 

If you need further assistance with that don't ask here, as said, ask on the Impact Discord.

**Comment by S-B99** [comment]
you can join the discord from this website https://impactclient.net
