### ISSUE TITLE
Please add a brief but descriptive title

### ISSUE THREAD

**Issue by Lexzach** [cabaletta/baritone#1624]
## Describe your suggestion
I would like an experimental setting that allows Baritone to attempt every Parkour move possible. This would make Baritone super fun for Parkour courses that involve jumps that Baritone won't attempt even if they are really easy for a non-Baritone player to do.

EDIT: It seems to be diagonal ascend jumps that mess it up.

## Settings
If applicable, what settings/customizability should be offered to tweak the functionality of your suggestion.
Maybe have the setting called .attemptAllParkour or something...?

## Context
Describe how your suggestion would improve Baritone, or the reason behind it being added.
It would make it a lot more fun for completing parkour because currently, Baritone cannot do most parkour courses from start to finish without placing/towering. Making it so a setting can toggle the ability for Baritone to attempt possible (but risky) jumps would be amazing!

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by UltraBlackLinux** [comment]
i like this idea too! would be a great addition, if baritone would do 4 block jumps, instead of cancelling the pathing.
There is a problem though, i expierienced. Baritone sometimes failes jumps and falls of the edge. doing this on a long parkour would cause several falls until completing. (This where id love an AI, that learns when the jumps fail, and corrects itself...)

**Comment by dominikaaaa** [comment]
There's a bunch of parkour settings already + you can disable block usage if you want it to figure out a way to parkour. It uses blocks and the such because that's the **fastest** way to get to the destination
