### ISSUE TITLE
Improvements to bridging across large gaps of terrain

### ISSUE THREAD

**Issue by DashGit** [cabaletta/baritone#163]
Currently, Baritone will occasionally build over gaps to more easily cross them. However, it does so in a way that I think could be improved upon. These features aren't truly necessary at all, but they would speed up pathfinding and would result in generally quicker times when travelling to a destination.

- Make Baritone's calculations consider that some large gaps can be crossed with the blocks in a player's inventory. Currently, Baritone will stop at the end of a decently-sized gap and say that it can't go any further. (This can be seen most prominently when in the outer End Islands and attempting to travel from one island to another). However, the gap could be crossed - it would just require a lot of building over with the blocks in the player's inventory. This is why it should consider that possibility when calculating a path.

- Use the technique called 'speedbridging' instead of normal bridging in order to build over to areas in general. This could be a toggleable setting, but this would definitely speed up bridging. ([here](https://youtu.be/72_9E5MO-Mg?t=2m54s)'s an example of what speedbridging/ninja bridging is incase anyone doesn't know.)

**Comment by leijurv** [comment]
Take a look at the settings, particularly `blockPlacementPenalty`. It defaults to 20 ticks, or 1 second, for placing a block for any reason. Try `blockPlacementPenalty 0` and it'll be MUCH less stingy about that.

Leaving this open for the speedbridging suggestion. For now, you can try turning on the setting `assumeSafeWalk` and enabling Safe Walk in Impact, that'll let it bridge faster at the cost of not always doing the right thing. For example, in the really weird scenario of bridging against a chest, when you sneak-backplace it'll right click instead of sneak+right click and will just open the chest lol.

**Comment by leijurv** [comment]
Speedbridging / ninja bridging has been added here https://github.com/cabaletta/baritone/commit/863ae447b9d36fb272d303c7e5babd2c361b8f49 actually. Closing =)
