### ISSUE TITLE
Mine Cocoa Beans but only Age 2

### ISSUE THREAD

**Issue by ralphchristianeclipse** [cabaletta/baritone#1854]
How do you mine with the data values

Example

#mine cocoa:age=2 ?

**Comment by dominikaaaa** [comment]
That's not a data value, that's an nbt tag, and you can't do that.

**Comment by UltraBlackLinux** [comment]
I already made a suggestion for that

**Comment by UltraBlackLinux** [comment]
#1660

**Comment by ZacSharp** [comment]
It is not nbt, it's the block state, which baritone does not support as well, but should since it is the successor of a supported mc feature.
The syntax used by mojang is namespace:name[blockStateProperty=value]{nbtProperty=value}.
Those properties in "[]" are the replacement of the old data value, which was removed in 1.13 and had not specific syntax but was (and is still) usually used with namespace:name:value or namespace:name@value
