### ISSUE TITLE
Does Baritone work with Fabric and or  Forge?

### ISSUE THREAD

**Issue by darkstar01** [cabaletta/baritone#1932]
I am trying to setup a new 1.16.1 server and I wanted to put Baritone on my computer so my 3 yr old son can mine diamonds without my help when I am at work, will Baritone work on Fabric or Forge? I know there was the Fabritone project but that is really buggy and not related to the development of Baritone, what are your suggestions for making this work well for him? (He can read pretty well at 3yrs old!)  (Yes I know you don't need a server, and the question isn't related to servers, but to installing Baritone on the client, or can the mod be placed on the server so its available to whomever logs in??)

Thanks ahead of time! <3 I love the project and am very impressed at the navigation skills of Baritone.

**Comment by dominikaaaa** [comment]
Baritone works as either a Forge mod or jar patch. It doesn't work on Fabric, and that's why Fabritone exists. The 1.16 branch is currently experimental and unreleased, I recommend you use 1.15.2 for now

**Comment by dominikaaaa** [comment]
Also, it's a client side only mod.

**Comment by CDAGaming** [comment]
"not related to the development of Baritone"

That stings, after my revent repository rebranding to explicitly state its a mirror to baritone. As the lead maintainer to fabritone, 1.16.1 on it is only unstable due to extended testing needed for Baritone, which Im also working on to ensure stability when i redo the port. 

Atm 1.16.1 is in stable condition but with major issues that can effect other versions that prevent any release until a proper investigation...

**Comment by Nikitka12XD** [comment]
There is a fork on Fabric, but it is only on 1.15.X https://github.com/WeNeedCoffee/Fabritone
