### ISSUE TITLE
ReplayMod Incompatible with Baritone

### ISSUE THREAD

**Issue by Zezypisa** [cabaletta/baritone#2084]
## Some information
Operating system: Windows 10 (amd64) version 10.0
Java version: Java: 1.8.0_51
Minecraft version: 1.16.3
Baritone version: 1.6.1
Forge mods (if used): None

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue
[latest.log](https://github.com/cabaletta/baritone/files/5398153/latest.log)

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
1) put the ReplayMod and Baritone into the Aristois mods folder and launch MC + Aristois
2) record a replay
3) When you try to watch a replay the game will crash

## Modified settings
To get the modified settings run `#modified` in game
AllowParkour - True
chatControl - false

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ehylo** [comment]
here is a log that wasn't using aristois and just had baritone and replay mod, it crashes when you try to watch a replay in the replay viewer https://paste.ee/p/HmdTw

**Comment by ZacSharp** [comment]
Looks like you are using Fabritone not Baritone

**Comment by l1ving** [comment]
This is a duplicate. Please search before creating an issue next time.

**Comment by CDAGaming** [comment]
@ZacSharp I'll say this one time. Baritone == Fabritone. The Fabritone name was also deprecated and no longer in usage and due to the parity, @leijurv did grant me usage of the Baritone name on the Fabric branch as well.

**Comment by ZacSharp** [comment]
@CDAGaming 
I wrote this based comments like https://github.com/cabaletta/baritone/issues/2027#issuecomment-695367125, https://github.com/cabaletta/baritone/issues/1997#issuecomment-687581760, https://github.com/cabaletta/baritone/issues/1972#issuecomment-679420872, https://github.com/cabaletta/baritone/issues/1969#issuecomment-678634310, https://github.com/cabaletta/baritone/issues/1940#issuecomment-669909322, https://github.com/cabaletta/baritone/issues/1938#issuecomment-669488116, https://github.com/cabaletta/baritone/issues/1934#issuecomment-668952951, https://github.com/cabaletta/baritone/issues/1918#issuecomment-665707502, https://github.com/cabaletta/baritone/issues/1871#issuecomment-658392492, https://github.com/cabaletta/baritone/issues/1858#issuecomment-655742037, https://github.com/cabaletta/baritone/issues/1844#issuecomment-653766086, https://github.com/cabaletta/baritone/issues/1842#issuecomment-653524895, https://github.com/cabaletta/baritone/issues/1841#issuecomment-653261984, https://github.com/cabaletta/baritone/issues/1835#issuecomment-652980300, https://github.com/cabaletta/baritone/issues/1828#issuecomment-650820847, https://github.com/cabaletta/baritone/issues/1821#issuecomment-649022387, https://github.com/cabaletta/baritone/issues/1705#issuecomment-630198452, https://github.com/cabaletta/baritone/issues/1608#issuecomment-618402461, https://github.com/cabaletta/baritone/issues/1540#issuecomment-612570022, https://github.com/cabaletta/baritone/issues/1365#issuecomment-596047133, https://github.com/cabaletta/baritone/issues/1362#issuecomment-595391388, https://github.com/cabaletta/baritone/issues/1335#issuecomment-592599196, https://github.com/cabaletta/baritone/issues/1299#issuecomment-586730687, https://github.com/cabaletta/baritone/issues/1284#issuecomment-591453060, https://github.com/cabaletta/baritone/issues/1257#issuecomment-578809281, https://github.com/cabaletta/baritone/issues/1188#issuecomment-566242607, https://github.com/cabaletta/baritone/issues/1106#issuecomment-547455377, https://github.com/cabaletta/baritone/issues/1105#issuecomment-547477890, https://github.com/cabaletta/baritone/issues/1090#issuecomment-586314153, https://github.com/cabaletta/baritone/issues/1080#issuecomment-544201520, https://github.com/cabaletta/baritone/issues/1075#issuecomment-544201555, https://github.com/cabaletta/baritone/issues/647#issuecomment-538704727 but maybe things changed.
Is this a combined issue tracker for both now or are issues *only* existing with fabric still invalid?
>  I'll say this one time.

This sounds a bit unfriendly to me. Did I get you wrong there or are you telling me that I'm dumb because I didn't get that fabritone is now supported here yet?

**Comment by l1ving** [comment]
It used to be that the "default" Fabritone people used was too difficult from Baritone to support it in this repo, and people were supposed to go to the Fabritone repo. 

Fabritone's vanilla branch is just Baritone with Fabric mappings and is allowed to use the Baritone name, and as such is supported here.

**Comment by ZacSharp** [comment]
ok, so changed mappings is ok, new features not
Thanks for the clarification

**Comment by l1ving** [comment]
different* not difficult, my bad

**Comment by CDAGaming** [comment]
@ZacSharp Yup! Since every fabritone feature was merged into Baritone officially, there's no further need to retain the Fabritone name, hence why in the repo, every occurrence of Fabritone's name (Except the repo name itself) was changed back to Baritone

**Comment by l1ving** [comment]
I'll make this info into an issue I can link in a bit

**Comment by l1ving** [comment]
I'll make this info into an issue I can link in a bit

**Comment by l1ving** [comment]
I'll make this info into an issue I can link in a bit

**Comment by l1ving** [comment]
Ooof rip my internet. What's the first version of Fabritone to be 1:1 Baritone @CDAGaming?

**Comment by CDAGaming** [comment]
https://gitlab.com/CDAGaming/fabritone/-/jobs/793196448

October 15th was the initial rollout that kicked off the migration that removed the Fabritone name and re-synced everything to be 1:1

**Comment by l1ving** [comment]
Thanks!

**Comment by leijurv** [comment]
If it is literally the exact same thing but with different mappings then I see no reason why the name should be different 😉 

There is something to be said for maybe fabric having a handful of differences from vanilla, just like forge. For example, when we first came up with the Forge build way back when, freelook didn't work on specific versions of forge and it was a huge massive pain in the ass to fix (the actual fix wasn't complicated, it was https://github.com/cabaletta/baritone/commit/7dd881aa9adc0dd8c39581540395279f21664dfb, but figuring out exactly what commit in what version of forge caused the issue was super annoying, as well as determining the workaround needed).

So, here's how I see it: Issues that only exist on baritone forge but not vanilla are valid, and shouldn't be closed. Issues that only exist in the presence of specific forge mods are borderline. This is not a clear cut case. Some patches (for example, https://github.com/cabaletta/baritone/commit/7e3a2d3c0a676ef955c1b345b1a789d51e8c6834) have the sole purpose of making Baritone more compatible with other Forge mods. Other times, the mod is Doing Something Weird. Replaymod appears to be creating a minecraft world object with certain fields set to null, judging from that stack trace? `java.lang.NullPointerException: null at baritone.cache.WorldProvider.initWorld`.

I think fabric should be treated the same way, ideally. I think in an ideal world we would want this remapping to be a build step, like how Forge for 1.15 is a build step that reruns with different mappings. Then the jars would be in baritone's official releases. At that point I would be 100% fine with fabric being treated exactly the same as forge has been, as I described ^. Until that point, I do not personally plan to handle issues that only exist on fabric (but maybe CDA might want to). Issues that only occur in the presence of specific other fabric mods should probably be ignored.

Issues that cannot be reproduced on the latest commit on any mainline MC version branch of this repo (baritone) should still be ignored unconditionally, IMO. This can include anything from the old Fabritone builds, or even old Baritone builds.

**Comment by ZacSharp** [comment]
So issues that only exist on fabric and are not specific to a mod are left open in case CDA wants to handle them?
Or should they be closed and redirected to the fabritone repo for CDA to handle them there?

**Comment by l1ving** [comment]
If it's on latest Baritone Fabric, then they should be opened here.

**Comment by ZacSharp** [comment]
Then it is 100% like Forge and Vanilla with other json patches except the main devs won't fix it

**Comment by l1ving** [comment]
Yes, but the issue is just as valid and someone else is free to fix it.

**Comment by avneh** [comment]
it doesnt work as i tries to fix it

**Comment by avneh** [comment]
Security problem maybe try taking out unnecessary stuff

**Comment by l1ving** [comment]
What???
