### ISSUE TITLE
Only 4 commands are working

### ISSUE THREAD

**Issue by TNT6161671** [cabaletta/baritone#2130]
Baritone does not work on me!

If i type .b farm/tunnel/click nothing happens.

Only goto, help, mine, stop are working.

Running on Minecraft 1.6.3 using the Aristois client.

Any solution?

**Comment by l1ving** [comment]
> using the Aristois client.

Aristois doesn't currently include Baritone, it only includes the buggy Fabritone.

**Comment by CDAGaming** [comment]
@l1ving I don't appreciate lies, especially with something I'm responsible for. And as I'm responsible for updating Baritone on the marketplace, I can personally tell you that the marketplace is supplying 1:1 Baritone, since as said multiple times before, Fabritone does not exist in any further instance and any usage of it can hop off the nearest recycling bin.

Additionally, the .b commands were helper commands made by deftware, not me. _So if it relates at all to deft's commands, then yes you can close the issue as non-related but otherwise this is still 1:1 baritone_

If there's one thing I as a software developer have no-tolerance for, it's people who either lie, or were too lazy to check the public maven or even my own prior words on this.

**Comment by l1ving** [comment]
Oh sorry, I thought it wasn't updated yet. I'll keep that on mind for the future, thanks for correcting me.

**Comment by CDAGaming** [comment]
With the stability of Fabritone at that time, the move was greatly given priority, and was announced in both Impact and Aristois' discord, but no harm no foul, just remember that Fabritone does indeed no longer exist as an entity and is now just "Baritone for Fabric"

The way you can ask someone on the difference, is with any Baritone chat command, as the prefix between the 1:1 version and Fabritone are different and a dead giveaway if they are on the older buggy version

**Comment by l1ving** [comment]
Well here they're using the impact prefix and I've also seen people change their fabritone prefix to # / baritone prefix to @
