### ISSUE TITLE
Pathfinding ignores world border

### ISSUE THREAD

**Issue by AdovinOFFICIAL** [cabaletta/baritone#218]
https://i.imgur.com/w6cdzfn.png

Self explanatory, world borders are ignored by Baritone and never changes or discontinues navigation.

**Comment by leijurv** [comment]
Why is the world border check split out based on the Moves dynamicXZ status? For dynamic XZ movements (Parkour), it's okay to calculate the cost of a jump outside the world border. We don't do this for unloaded chunks, because a Parkour into empty chunks will 100% fail, there's nowhere to land on. And only after we calculate the cost do we know how far it really went. So in this case, we check if the world border entirely contains the real destination x and z (res.x and res.z) instead of newX and newZ (which assumes a full 3 gap jump)
