### ISSUE TITLE
Baritone ignores most obvious path

### ISSUE THREAD

**Issue by Talhoid** [cabaletta/baritone#2283]
I'm trying to make baritone path here:
![2020-12-20_12 28 54](https://user-images.githubusercontent.com/68508139/102720183-d767f300-42c0-11eb-91b8-97bba4bf8502.png)

But it goes in the complete opposite direction:
![2020-12-20_12 28 57](https://user-images.githubusercontent.com/68508139/102720195-ecdd1d00-42c0-11eb-848a-951eefb682f9.png)
It could've just jumped down!
Why is it doing this???

**Comment by scorbett123** [comment]
enable #allowParkour. This will make it so that baritone will be willing to jump down. However while using baritone remember that it hasn't be told all possible movements so in some places it will take less direct routes then what a human would take ( however in others it takes a more direct route.)

**Comment by l1ving** [comment]
Next time fill in the template.

**Comment by Talhoid** [comment]
I have enabled allowParkour and it wont work

**Comment by l1ving** [comment]
Read my previous comment
