### ISSUE TITLE
hunting, eating and removing items

### ISSUE THREAD

**Issue by cusscussyt** [cabaletta/baritone#2289]
can you add a feature where it can hunt mobs and animals like say i need food i could just tell it to hunt for cows also could you add it so it automatically throws out things when full or goto home and  put your stuff in a chest you have specified. also have it when you get to 3 bars of hunger it automatically eats if you have food in your inventory if you could add those 3 things i would be very gratful

**Comment by l1ving** [comment]
1. There is the issue template which you have so kindly ignored and deleted
2. Several of these things have already been suggested, if you used the search bar to the left of the Create Issue button 
3. The rest of the items which haven't been suggested are already features in the likes of Impact / KAMI Blue
4. And because said features are out of scope for Baritone, you should use those alternatives instead
