### ISSUE TITLE
baritone stops tunneling if it encounter holes/ravines

### ISSUE THREAD

**Issue by edyxrp** [cabaletta/baritone#2318]
## Some information
Operating system: Windows 10
Java version: 1.8.0_271
Minecraft version: 1.16.4
Baritone version: 1.6.2
Forge mods (if used): 

## Exception, error or logs

While tunneling baritone will freeze in place if it encounters a hole in the tunnel direction
How do i tell it to make a bridge under him in order to continue tunneling

[2020-12-31-2.log.gz](https://github.com/cabaletta/baritone/files/5759404/2020-12-31-2.log.gz)

## How to reproduce

#tunnel 3 1 600

## Modified settings

nothing all default

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by m-sarabi** [comment]
The same thing happened to me while I was digging out a chunk. I selected the chunk and started the cleararea with reverse layer order. it did a pretty great job at first and then after reaching some caves it suddenly broke, it stood at one spot doing nothing.

After testing a lot of unrelated things and failing of course, finally I turned on the chat debug (XD) and realized that it had a goal that was empty. I simply placed a block at that spot and It temporary started mining again before it stopped at another spot. Well the thing is that as of 1.13 caves and underground structures generate **minecraft:cave_air** instead of air inside them. so by simply adding the cave_air into the buildIgnoreBlocks list suddenly everything started working again.

**Temporary solution:** Add cave_air in the buildIgnoreBlocks

**Solution:** Baritone should treat **air**, **cave_air** and **void_air** the same.

**Comment by SylveonBottle** [comment]
Having this issue with `#sel fill cobblestone`.

Note: `#buildinlayers` was disabled at first, resulting in baritone building upwards like it does. I then enabled it to allow it to build in layers.
Notice how baritone builds a wall of cobblestone upwards- however, it ignores the spot on the left. This was part of a cave system, and contains `cave_air`, which baritone can not (or does not) place cobblestone in.

![Untitled](https://user-images.githubusercontent.com/17802843/110973139-c1fce500-8354-11eb-8571-32b56f60f2da.png)

I would make a new issue about this, however the solution to this issue's problem could potentially solve the problem I'm experiencing.

That being said, I do want to make it perfectly clear: **This affects `#sel fill`**

**Comment by SylveonBottle** [comment]
Another screenshot showcasing a cave blocking `#sel fill cobblestone`'s intended purpose.

**Comment by ZacSharp** [comment]
This issue is well known, just like it's cause and a fix that is already implemented in a pr. Please don't open another issue for it.
