### ISSUE TITLE
Baritone on mcp eclipse

### ISSUE THREAD

**Issue by Virusnest** [cabaletta/baritone#2337]
Hi I am making a hacked client using eclipse and mcp in 1.12 and I am wondering how to add baritone to my client in eclipse

**Comment by Virusnest** [comment]
Note: 
Raw mcp,. no forge

**Comment by l1ving** [comment]
No

**Comment by Virusnest** [comment]
What why

**Comment by Virusnest** [comment]
What why

**Comment by l1ving** [comment]
MCP violate's Mojang's EULA

**Comment by Virusnest** [comment]
Umnno not if you plan to sell it or put the source code Online and it was created by a Mojang employe

**Comment by Virusnest** [comment]
So not against the eula

**Comment by Virusnest** [comment]
And making a jar and giving it to people is not distributing the game because you need to own the game to use it

**Comment by l1ving** [comment]
We don't provide support for EULA violating projects.

**Comment by Virusnest** [comment]
What about impact

**Comment by Virusnest** [comment]
Or forge or anything not Vanilla

**Comment by Virusnest** [comment]
Also look at this
https://minecraft.gamepedia.com/Michael_Stoyke

**Comment by Virusnest** [comment]
Also this is for personal use I do not wish to distribute the finished product I am only using the client for 2b and other clones for my own use

**Comment by Virusnest** [comment]
Also forge uses mcp and according to you forge therefore brakes the Mojang EULA and you are a contributor on a forge client therefore you are part of a EULA breaking project

**Comment by l1ving** [comment]
> And making a jar and giving it to people is not distributing the game because you need to own the game to use it

"Making a jar and giving it to people" is the definition of distributing. 

> Also forge uses mcp and according to you forge therefore brakes the Mojang EULA and you are a contributor on a forge client therefore you are part of a EULA breaking project

Forge uses MCP **mappings** when *decompiling on your local machine* which is **never** distributed. Forge mod jars do not contain Mojang code. MCP mods ("jarmods") *do* contain copyrighted Mojang code.

> What about impact

Again, Impact does not distribute Mojang code. Instead, it uses it's own loader which they made called [ClientAPI](https://github.com/ImpactDevelopment/ClientAPI/) and works much in the same way Optifine does, *by modifying the existing Minecraft jars on your computer*. Mojang code is not distributed via Impact's jar using this method, instead it has to be downloaded using the official launcher beforehand.

> Or forge or anything not Vanilla

"Anything not vanilla" is an extremely broad term and could mean, *literally*, "anything", meaning it could or couldn't violate Mojang's EULA. 

Now I suggest you stop acting smart because you clearly don't even understand Mojang's EULA, and you will not be given help for making an MCP client (ie jarmodding) because even if you do say you won't give the jar to other people, we **cannot** regulate that. If you continue to ask for help with violating the EULA you will be banned from this repository.
