### ISSUE TITLE
Forge 1.12.2 won't launch at all

### ISSUE THREAD

**Issue by lRoberth** [cabaletta/baritone#2339]
## Some information
Operating system: W10 Pro
Java version: 1.8.0_261-b12
Minecraft version: 1.12.2
Baritone version: 1.2.14
Forge mods (if used): [Mods used here](https://i.imgur.com/M1nZihX.png)

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue
[latest.log](https://github.com/cabaletta/baritone/files/5785045/latest.log)

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
1.- Install Baritone 1.2.14 and MixinBootstrap 1.0.5
2.- Launch Forge
3.- Launcher window disappears and game never launches. I have to kill it using task manager.

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
> org.spongepowered.asm.launch.MixinInitialisationError: Required mixin config mixins.bewitchment.json requires mixin subsystem version 0.8

Did you even read your own log?

**Comment by lRoberth** [comment]
> > org.spongepowered.asm.launch.MixinInitialisationError: Required mixin config mixins.bewitchment.json requires mixin subsystem version 0.8
> 
> Did you even read your own log?

I did, and that's why I'm here. I don't know what it means by "ModLauncher is not available".
If I remove baritone from mods, it perfectly works fine, so I'm definitely missing something.
If there was more detailed documentation about forge versions on Minecraft 1.12.2 I'm pretty sure I wouldn't be here.

**Comment by l1ving** [comment]
> I don't know what it means

It means another mod requires a version of Mixins which is newer than what Baritone provides. Because Baritone is alphabetically before Bewitchment, it will load it's version of Mixins first (0.7), and when Bewitchment goes to load it will throw the error "Hey!! I require version 0.8, and Mixins 0.7 was loaded before I could load".

A solution on your end could be to rename the Bewitchment jar to include a `!` at the beginning of it's filename, to ensure that it loads first. 

> more detailed documentation about forge

Well tough luck, Lex is an asshole and couldn't even keep for previous shitty documentation online, whatever javadocs there were left. And this doesn't have much to do with Forge, it's literally just saying "... requires mixin 0.8", which I assume could be slightly confusing if you don't know why it doesn't have 0.8 (Baritone loaded first) or if you don't know what Mixins are.

**Comment by lRoberth** [comment]
That fixes it, thank you.
