### ISSUE TITLE
How to make baritone run away from mobs?

### ISSUE THREAD

**Issue by turret001** [cabaletta/baritone#2417]
## What do you need help with?
How can I make baritone run away from mobs? I tried using #avoidance and set it to true but it still doesn't care about hostile mobs
Minecraft 1.16.4
Forge 35.1.36
Baritone v1.6.2

https://user-images.githubusercontent.com/24281147/106603569-801b9a80-656f-11eb-8f9a-bd1e22d789e9.mp4

this is my settings.txt for baritone:
```
avoidance true
mobAvoidanceCoefficient 4.0
mobAvoidanceRadius 12
freeLook false
legitMine true
```

## Final checklist
- [x] I know how to properly use check boxes 
- [X] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
set the modAvoidanceCoefficient really really high i.e. 1000, then it should decide to run away, legit mine will probably make this not  work though. FYI avoidance just increases the cost inside that area, it doesn't mean that it won't go near mobs, just that there is a lower likelihood.

**Comment by turret001** [comment]
thank you!

**Comment by bphd** [comment]
The system how it's done right now is not really good enough, it has many flaws

Like, it sometimes have difficulties with chunks and monster that appears too late in its path calculations, and it won't update it upon their apparition, so it will pass through monster totally ignoring them and failing the purpose

And worse, if the coefficient is too high, it won't be able to establish any path near monsters (that is has ignored earlier) because every paths would be too expensive for him and it will prefer to abort and just stay dying among monsters

And for the radius it's complicated aswell. With how monsters spawns it becomes easy to be trapped if you set a radius to not be seen by them (because a big coefficient will deny the possibility to pass by them). And if you set a tiny radius it fails the purpose basically because being detected; and because, as said earlier, it won't recalculate path often, it will just pass through monsters if they pursue you without trying to dodge them

Solution would be way more frequent path reevaluation, to be able to play while being detected because dodging them

Or even better, an auto shield that block any projectile or contact, that is fast enough that it can mine while blocking when it happens so it can still flee

Depends on what @leijurv think about it
