### ISSUE TITLE
Schematic support for 1.16.5 forge

### ISSUE THREAD

**Issue by DemandedFanatic** [cabaletta/baritone#2491]
As far as I can find there is no way to use the schematic functions in 1.16.5 forge, as there is no version of either schematica or litematica for that version. Is that the case, or am I just blind? Also, if it is the case that there isn't any way to use it currently, are there any plans to simply bake that functionality in to begin with?

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
no and yes

**Comment by ehylo** [comment]
I'm pretty sure world edit (supports 1.16.5 forge) and litematica are the only way to load the old mcedit format (<=1.12.2 *.schematic) in newer versions and world edit but not litematica supports the newer sponge format (*.schem). It shouldn't be possible to make a .schematic file with 1.13+ blocks because world edit does not make .schematic files it makes .schem (sponge format) files but somehow people on the schematic websites manage too, they say they used world edit but I believe they change the file extension or there is some other application I do not know of that makes .schematic with 1.13+ blocks which breaks baritone as when you say to build with .schematic is thinks it is an old mcedit schematic and therefore fails to load the schematic, this is fixed by changing the file extension back to what world edit did, .schem. I sorta suggested in the Impact discord that maybe add additional syntax to specify the type of schematic format (sponge/mcedit and maybe litematics if #2338 is ever merged) so that way you could load these changed extension files regardless of what the extension is, or an even simpler solution is to just try the other formats automatically, so instead of failing it tries the other one and probably will work.
