### ISSUE TITLE
Create Highway Digger Mode

### ISSUE THREAD

**Issue by EvilSourcerer** [cabaletta/baritone#253]
Hey, I would love it if baritone had a highway digging feature! I don't care if it does not support diagonals, but because the current version of Baritone tries to go through open nether rather than digging highways, I would love to know if there is a way to program a highway digger mode, which would automatically replace any lava in the way or just avoid it if AllowPlace is enabled. 

Or is there a way to make it keep y axis that i'm not aware of?

**Comment by leijurv** [comment]
There is! Make sure simplifyunloadedycoord is false then set a goal with a y coord of 120 like  1000000 120 0 or something. This won't make it replace lava though, it never breaks any block touching lava. And it will use caves if it makes it faster, it won't just dig for no reason, also make sure it has a fast pick otherwise it will dip down into open nether more often

**Comment by EvilSourcerer** [comment]
Thank you for the reply! Is it possible to make it more of a straight line, just so that there is no risk of it dying in open nether? It would be great I could AFK mine the highway.

**Comment by EvilSourcerer** [comment]
thank you! That's exactly what I was hoping for!

**Comment by Thunder33345** [comment]
maybe something like a proper implementation as this seems quite useful?
like maybe a "behavior mod" and even outsource it to 3rd party devs

**Comment by EvilSourcerer** [comment]
hmm that may also be a good idea...

**Comment by Thunder33345** [comment]
if it's something 3rd party devs can interface with it would be cool to have things like
highway digger, afk fish while tending to crops, not sure what more but this is more in the side of flexibility
