### ISSUE TITLE
Settings of Baritone

### ISSUE THREAD

**Issue by WalterWhiteDrugDeal** [cabaletta/baritone#2538]
It would be nice if there was another setting like the setting that tells baritone not to break blocks, but instead of just trying not to break the block it actually doesn't break the block no matter what. I guess it could be @settings NeverBreakBlock idk just a suggestion.

**Comment by l1ving** [comment]
What do you think `#allowBreak` does

**Comment by WalterWhiteDrugDeal** [comment]
Doesnt that allow baritone to break blocks?

**Comment by WalterWhiteDrugDeal** [comment]
> What do you think `#allowBreak` does

Doesnt that allow baritone to break blocks?

**Comment by l1ving** [comment]
> I think you need to read what I said again. 

get betterer english then

`#blocksToAvoidBreaking`

**Comment by ehylo** [comment]
I think what WalterWhiteDrugDeal is trying to suggest is there to be a command that actually forces baritone to not mine the specific list of blocks, currently with `blocksToAvoidBreaking` baritone will try to avoid these blocks but in some cases (actually most) it still breaks them, there are several issues where this has been mentioned as intentional, like in #1427 where 
> If it seems that the goal cannot be achieved by another path, it will break those blocks. Please close this issue, this is not a bug, this is intentional.

so this suggestion is to add another command to make it never break those specific blocks no matter if the goal could be reached or not, there are many still open issues where this has been suggested (like #756)/reported as a bug so this whole thing is just a mess lmao

**Comment by l1ving** [comment]
> there are several issues where this has been mentioned as intentional, like in #1427 where

Incorrectly. It's actually a bug, as referenced in more recent issues.

**Comment by WalterWhiteDrugDeal** [comment]
> > I think you need to read what I said again.
> 
> get betterer english then
> 
> `#blocksToAvoidBreaking`

"betterer" thats kind of contradictory considering it seems you dont have great grammar either. Also English is with a capital e and betterer is not a word. Also what do you mean incorrectly? I believe you could remove "incorrectly" and the sentence will hold the same meaning.

**Comment by WalterWhiteDrugDeal** [comment]
> I think what WalterWhiteDrugDeal is trying to suggest is there to be a command that actually forces baritone to not mine the specific list of blocks, currently with `blocksToAvoidBreaking` baritone will try to avoid these blocks but in some cases (actually most) it still breaks them, there are several issues where this has been mentioned as intentional, like in #1427 where
> 
> > If it seems that the goal cannot be achieved by another path, it will break those blocks. Please close this issue, this is not a bug, this is intentional.
> 
> so this suggestion is to add another command to make it never break those specific blocks no matter if the goal could be reached or not, there are many still open issues where this has been suggested (like #756)/reported as a bug so this whole thing is just a mess lmao

Yes that is exactly what I was trying to say.
