### ISSUE TITLE
Digging blocks eventually falls into lava

### ISSUE THREAD

**Issue by EvilSourcerer** [cabaletta/baritone#254]
If you leave Baritone mining in the nether, for some reason it inevitably falls into a lava pocket. Not much to describe the problem. Simply try it yourself and it does that.

**Comment by leijurv** [comment]
What is costHeuristic set to?

**Comment by EvilSourcerer** [comment]
20

**Comment by EvilSourcerer** [comment]
(Although it shouldn't fall into lava in any case)

**Comment by leijurv** [comment]
By "falls into a lava pocket" do you mean it just mines into one at foot level? Or it mines into one just below foot level and falls? Does this happen while it's mining a tunnel or when it's following a path through a cave or open area? Can you make it happen reliably? I can't make it happen. Maybe a screen recording?

**Comment by EvilSourcerer** [comment]
It mines into one at foot level. This happens when digging the highway. It happened to me multiple times with efficiency 4 pickaxes. It may be possible that it happens with unenchanted pickaxes but I haven't been digging long enough for a solid conclusion. I actually recorded the stream when it happened so here is the stream. Pay attention at 39:12 and 1:18:39

**Comment by leijurv** [comment]
<img width="1219" alt="screen shot 2018-11-09 at 3 48 29 pm" src="https://user-images.githubusercontent.com/3837873/48294055-f5eb3700-e436-11e8-96d0-f9e4eba75c8a.png">

<img width="1216" alt="screen shot 2018-11-09 at 3 48 39 pm" src="https://user-images.githubusercontent.com/3837873/48294056-f7b4fa80-e436-11e8-9400-0919ab761ad2.png">

So my analysis is that your pickaxe is just too damn fast... seriously.

The path that it calculated turned left one block before the lava, but as it was breaking the blocks, it held down left click for perhaps one tick too long, and it broke one block more than it intended.

For the first instance at 39:12 it's **really** hard to tell what's going on, I've gone through it frame by frame several times, and I'm reasonably sure that it planned to descend one y-level before the lava, then ascend back up afterwards. However, again it broke two blocks too far while breaking.

For now, use a lower efficiency pick for safety.

costHeuristic will have no effect on this. 

Furthermore, (i know this is crazy), but block breaking happens in a different mode based on if the chat text input box is open or not, when it's closed it simulates holding down left click and breaks blocks as vanilla, when it's open it has to bypass this and it sends click blocks to the player controller directly. So leaving the in game chat window closed should actually make it more reliable. 

I'm also going to commit something that should fix, where it won't start left clicking until objectMouseOver matches. 

Thanks for the report!

**Comment by leijurv** [comment]
So that you don't have to wait until Impact 4.5, I have backported the fix to the impact4.4-compat branch. The cherry picked commit is here: https://github.com/cabaletta/baritone/commit/1335562075acd3564a69b82101d4c2580bbe1a02

You can build impact4.4-compat yourself, or download from here https://www.dropbox.com/s/bh116t47a52x0x4/baritone-api-1.0.0-hotfix-3.jar?dl=0


To replace the jar in Impact 4.4, follow the instructions from the readme. Pasted here: 

For example, to replace out Impact 4.4's Baritone build with a customized one, build Baritone as above then copy `dist/baritone-api-$VERSION.jar` into `minecraft/libraries/cabaletta/baritone-api/1.0.0/baritone-api-1.0.0.jar`, replacing the jar that was previously there. You also need to edit `minecraft/versions/1.12.2-Impact_4.4/1.12.2-Impact_4.4.json`, find the line `"name": "cabaletta:baritone-api:1.0.0"`, remove the comma from the end, and entirely remove the line that's immediately after (starts with `"url"`).

**Comment by EvilSourcerer** [comment]
Thanks for the support!
