### ISSUE TITLE
Baritone will not build what I want

### ISSUE THREAD

**Issue by riceProblem** [cabaletta/baritone#2541]
## Some information
Operating system: Windows 10
Java version: 1.8
Minecraft version: 1.12.2
Baritone version: 4.9.1
Forge mods (if used): 

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue
[profile-results-2021-03-06_16.16.15.txt](https://github.com/cabaletta/baritone/files/6096339/profile-results-2021-03-06_16.16.15.txt)

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
I do not think you can reproduce. I was trying to build with baritone and it said I didn't have the materials to build what I wanted, but I checked and I do.
## Modified settings
To get the modified settings run `#modified` in game
allowParkour true
allowParkourPlace true
allowPlace false
allowWaterBucketFall false
chatControl false
legitMine true
legitMineIncludeDiagonals true
maxFallHeightBucket 5
maxFallHeightNoWater 5
planAheadPrimaryTimeout 100
primaryTimeout 100
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
1. How did you find a profile result in `%appdata%/.minecraft/logs/`?
2. Add your steps to reproduce anyway, if you don't provide them it's not even possible to try it and without reproducing it there's no fixing it (and this issue is invalid automatically)
3. Now to you problem itself: I'll assume you did some dumb mistake (no steps that show you didn't) and tell you to either get that stuff into your hotbar yourself or turn on `allowInventory` and make sure you have everything you need in your inventory, because Baritone can neither use your chests nor obtain the materials by any other means. If that's not your problem then fill out that template and provide a log (not a profile result).
