### ISSUE TITLE
Woah what happened here?

### ISSUE THREAD

**Issue by EvilSourcerer** [cabaletta/baritone#266]
What happened? It just fell... 
https://www.youtube.com/watch?v=cSFoiWg22-A look at 1:51:32

**Comment by leijurv** [comment]
Cannot reproduce...

Tried both current Baritone master:
https://youtu.be/3Vi9XFkmglo

And the version in Impact 4.4 (which is v1.0.0-hotfix-3)
https://youtu.be/AXUuA01x29A


Also, unrelatedly:
<img width="1220" alt="screen shot 2018-11-21 at 10 05 23 am" src="https://user-images.githubusercontent.com/3837873/48860180-07a4d680-ed75-11e8-9a4d-0f0394591273.png">

The center of your monument is at -375001 0 not -375000 0... you're standing at -375000.6 but that's block -375001 because it rounds down, not towards zero, so negative numbers round to even lower (farther from zero).

<img width="173" alt="screen shot 2018-11-21 at 10 06 18 am" src="https://user-images.githubusercontent.com/3837873/48860235-2b681c80-ed75-11e8-8445-2b1226a785f9.png">

**Comment by EvilSourcerer** [comment]
Oh that monument was lazily done lol. Anyway, I used the default Impact 4.4 baritone with default settings except for a costHeuristic set to 20. It is not known to me why this is a thing. Might want to leave this in the back of your mind so you can reference it later.

**Comment by leijurv** [comment]
Yeah, thank you. Increasing the cost heuristic changes what paths it finds, but not how it executes them. That was just a series of traverses, followed by a series of pillars, with sprint on. I don't really know what happened there tbh. I'm going to see about adding some stabilizing to pillar in general (i.e. something like "don't hit space until your velocity is less than 0.01" or something, so that it comes to a stop before jumping) should help this and other weird pillar issues.

**Comment by leijurv** [comment]
https://youtu.be/OLAvEabDHRc

https://youtu.be/xvo2jo9NQ_E

Fixed! yay.
