### ISSUE TITLE
Can't build 1.6.3 due to a file that 404s?

### ISSUE THREAD

**Issue by thecakeisalie25** [cabaletta/baritone#2709]
## Some information
Operating system: Arch linux (via WSL)
Java version: OpenJDK 8
Minecraft version: 1.16.5
Baritone version: 1.6.3
Other mods (if used): N/A, but building for forge.

## Exception, error or logs
[setupDecompWorkspace.log](https://github.com/cabaletta/baritone/files/6410512/setupDecompWorkspace.log)
[refresh-dependencies.log](https://github.com/cabaletta/baritone/files/6410513/refresh-dependencies.log)
[build-Pbaritone.log](https://github.com/cabaletta/baritone/files/6410511/build-Pbaritone.log)
[build.log](https://github.com/cabaletta/baritone/files/6410510/build.log)

Both of the build* logs seem to point to the file `https://files.minecraftforge.net/maven/com/github/ImpactDevelopment/Vanilla/1.16.5_mapped_snapshot_20201028-1.16.3/Vanilla-1.16.5_mapped_snapshot_20201028-1.16.3.jar`, which 404s. 

If I'm going about this wrong, please let me know the correct build instructions, thanks. I'm new to gradle, and java in general, especially for minecraft. 

## How to reproduce
Clone repo
`git checkout 1.16.5`
`./gradlew setupDecompWorkspace` -- Fails, task not found in root project 'baritone'
`./gradlew --refresh-dependencies` -- Seems to work OK.
`./gradlew build -Pbaritone.forge_build` -- Fails due to a missing "Vanilla.jar", check the logs section.
`./gradlew build` -- Same as ^

## Modified settings
No files modified from the 1.16.5 branch.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
The issue is not the file not existing (it does as far as I know) but gradle not searching in the right place.
I don't know what could cause this issue so I can't help any further than suggesting
* trying again with a fresh copy
* clearing the gradle cache
* trying to build either on a true Linux or directly on your windows (gradle can run on windows, right?)
* any combination of those points

**Comment by thecakeisalie25** [comment]
Gradle says it's searching `https://files.minecraftforge.net/maven/com/github/ImpactDevelopment/Vanilla/1.16.5_mapped_snapshot_20201028-1.16.3/Vanilla-1.16.5_mapped_snapshot_20201028-1.16.3.jar` for this file. My browser says that it 404s, but that might just be me. Can you check it out? 

I've tried again with a fresh copy and the same issue results. I've tried `./gradlew clean` and then the steps above, idk if that's how you clear your gradle cache. I've got no access to bare metal linux machine, but I could try in a VM if you'd like.

**Comment by ZacSharp** [comment]
Of course you get a error 404 there because Forge doesn't host files for impact. As I said, gradle is searching the wrong place and I have no idea why. I successfully built Baritone just a few minutes ago.
`/gradlew clean` only cleans the build output, not the cache. On linux the cache should be in `~/.gradle/caches/`, for Windows I don't know.
I don't really  expect a difference between WSL and a VM and would rather test directly on the Windows machine, but maybe you have reasons to not do so (e.g. gradle doesn't work on windows, I use Linux so I dunno).
Did a successful build (with and without deleting the cache).

**Comment by scorbett123** [comment]
On windows it is in C:/Users/<USER>/.gradle/caches/

**Comment by thecakeisalie25** [comment]
Retried the build after deleting Gradle cache, re-cloning (and checking out the 1.16.5 branch), same issue, same file it's missing.

I can build the master branch just fine, this issue is specific to this branch.

**Comment by thecakeisalie25** [comment]
Retried it on an arch vm, works fine there. Weird.

**Comment by Flurrrr** [comment]
@thecakeisalie25 I ran into the same problem, did some googling of the errors and someone said to add `--no-daemon` which did work, no clue if this is bad but it worked for me so you may want to give it a try.
