### ISSUE TITLE
Baritone compatibility error with Wurst

### ISSUE THREAD

**Issue by 7Xx9XrPn1B** [cabaletta/baritone#2748]
## Some information
Operating system: Windows 10 Pro (64-bit)
Java version: 8 Update 291 (64-bit)
Minecraft version: Fabric 1.16.5
Baritone version: api-fabric-1.6.3 (1.16.5)
Other mods (if used): Used Wurst-Client-v7. 15-MC1. 16. 5

## Exception, error or logs
[latest.log](https://github.com/cabaletta/baritone/files/6489381/latest.log)

## How to reproduce
1. Install Fabric mod Wurst-Client-v7. 15-MC1. 16. 5 and baritone-api-fabric-1.6.3
2. Enter the #help command in the chat.
3. Click on any clickable text.

## Modified settings
The settings do not affect the error.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by TheAwesome98-Real** [comment]
1. there are invalid characters in that bug report
2. wurst does not cause that

**Comment by wagyourtail** [comment]
and yet I was able to reproduce this, wurst intercepts and breaks chat messages too early

**Comment by ZacSharp** [comment]
> 2. wurst does not cause that

looked at the files @wagyourtail mentioned and I think this is indeed caused directly by wurst and not a mixin conflict. Wurst just cancels the method and sends the message itself instead of allowing the vanilla behaviour (or Baritone, which hooks in slightly later than wurst) to happen.

So unless someone proves me wrong this can be closed and should be reported on the wurst bug tracker instead.

**Comment by TheAwesome98-Real** [comment]
oh wait my client uses a similar mixin, that’s why that bug occurs for me too

**Comment by ZacSharp** [comment]
After reading the edit history of @wagyourtail's comment I'm now pretty sure this is not a Baritone error but a Wurst error and should be reported on their bug tracker accordingly.
I think we could try moving Baritones injection point to an earlier point, but as far as I know (and that's not much for mixins) that would only make it depend on the order of mixin application instead of fixing it reliably.
