### ISSUE TITLE
How do you do this

### ISSUE THREAD

**Issue by Swiftform** [cabaletta/baritone#2753]
How do you change the code?

**Comment by ZacSharp** [comment]
To change the code use some sort of text editor IDE, batch text processor whatever you like. (some of these options might be useless in most cases)

Since I assume you actually want know how to download, build, etc:
https://github.com/cabaletta/baritone/blob/master/SETUP.md#build-it-yourself and use an editor or IDE of your choice to edit the code in /src before running `gradlew build` / `gradlew build -Pbaritone.forge_build` / `gradlew runClient` (command line) or double clicking **build** (IntelliJ).
And just in case you want to edit the code in this repo and not locally:
Use the fork button on the top right of your screen and apply https://github.com/cabaletta/baritone/blob/master/SETUP.md#build-it-yourself to your own repo instead, using git and *not the zip download*. After you have done your changes commit them using git, push to your github repo and make a pull request. And please don't create junk pull requests like #2668.

**Comment by ZacSharp** [comment]
I really should've just closed this as invalid with just my first sentence. Don't know why I've written almost a full essay for something that wasn't asked.
