### ISSUE TITLE
world saving event

### ISSUE THREAD

**Issue by ItsYoungDaddy** [cabaletta/baritone#2767]
## What do you need help with?
can world saving be turned of? i set save chunks to 0 but it still always says its saving in my logs and its hard to go thru my crash reports to find if something went on earlier 

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
Where did you find a setting called "save chunks"??
To disable chunk caching set `chunkCaching` to false. It will still output *"Started saving the world in a new thread"* but should output *"Not saving to disk; chunk caching is disabled."* directly after that rather than *"Saving region \<x\>,\<z\> to disk \<path\>"* and *"World save took \<ms\>ms"*.
You can disable `containerMemory` as well, but you won't see any difference in the log files.
