### ISSUE TITLE
Minecraft  Crashes when Baritone is installed

### ISSUE THREAD

**Issue by ravioliboy13** [cabaletta/baritone#2797]
## Some information
Operating system: Windows 10 Latest
Java version: version 8 Update 261
Minecraft version: 1.12.2 Forge 14.23.5.2855
Baritone version:  1.2.15
Other mods (if used): FTB Ultimate Reloaded Modpack v1.11
[latest.log](https://github.com/cabaletta/baritone/files/6631577/latest.log)

## How to reproduce
Just Install with the Modpack FTB Ultimate Reloaded any version and any Launcher run it.

## Modified settings
None, couldn't run it...

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
Huge modpacks are likely to contain incompatible mods (more mods, bigger chance), especially since they tend to contain (primarily optimization) mods that change a lot in minecrafts code, causing incompatibilities with other injectors (e.g. Baritone although it doesn't do much). Unless you have control over the modpack (i.e. it's not a server pack) there's likely not much you can do.

Also, to have a chance to fix the error, especially if "fixing" it by removing a mod, it helps to know which mod causes the crash (together with Baritone), so try removing mods until you know the minimum required set of mods to cause the crash.

**Comment by thecakeisalie25** [comment]
It seems to be phosphor, from the log.

if that's not the case, try bisecting your mods folder repeatedly.

If you have 100 mods, remove mods 1-50. If the issue still persists, remove mods 50-75. If it works fine with 1-50 removed, put them back and remove 1-25. Etc, each time cutting the pool of mods it could be in half. If you find which mod may have caused it, I'd be interested to know.

**Comment by ravioliboy13** [comment]
After 20 mins of trouble shooting I found the culprit it’s Phosphor Forge apparently it optimizes Minecraft, I guess that could be it

**Comment by ravioliboy13** [comment]
Would the unoptimized Version work?

**Comment by thecakeisalie25** [comment]
That's what I suspected based on the log files. It's just a client-side optimization, so you should be fine to play without it (joining servers and such) as it only modifies files client-side, assuming your computer can handle the default unoptimized lighting.

> 
> 
> Would the unoptimized Version work?

Do you mean the unoptimized version of baritone? If so, no, the unoptimized version shouldn't fix anything, it's just baritone code that is unoptimized, which only really helps for debugging issues with baritone itself during development. From the looks of things it seems like removing phosphor is going to be the best solution.

**Comment by ravioliboy13** [comment]
Yeah removing Phosphor is a good option I was suspecting something in that direction too
