### ISSUE TITLE
How do I allow baritone to mine netherite with fire res 

### ISSUE THREAD

**Issue by cybersauce640** [cabaletta/baritone#2837]
When I’m mining for netherite using baritone. It only mines the netherite that is not surrounded by lava, so I made fire res so I don’t die when baritone mines netherite surrounded by lava. But baritone still dosent’ mine it so I want to know if there is a setting that allows baritone to mine the netherite even if it is surrounded by lava.

**Comment by ZacSharp** [comment]
This is not possible and I think it isn't what you want either, because Baritone would mine the ore and then be stuck in lava, since it can't move through flowing liquids.
What you really want is probably Baritone automatically removing the liquid before mining adjacent ores, which has already been suggested in #2827.
