### ISSUE TITLE
Automatic updates when Impact 4.5 releases

### ISSUE THREAD

**Issue by EvilSourcerer** [cabaletta/baritone#291]
Create a update module in baritone, which will do the following when Baritone launches : 

- Download the `CurrentVersion` file from the Github repo, which you can add manually ( Download response from https://raw.githubusercontent.com/cabaletta/baritone/master/CurrentVersion.txt as a string)

 - Have a builtin variable called `VersionNumber`.

 - Check the checked version against `VersionNumber`.

 - If it detects an update, have it display a GUI when the game loads asking if you would like to update. (This may be difficult to do)

 - If the user presses 'Download & install update' then impact will quit, then it will launch a special `update.jar` file which will automatically save the new version to the previous baritone file.

**Comment by leijurv** [comment]
brady doesn't trust like that

**Comment by leijurv** [comment]
any auto update would be in impact itself, not in baritone

**Comment by 0-x-2-2** [comment]
and impact can already do this

**Comment by leijurv** [comment]
`There are way too many cool fixes for baritone to update with every major impact version.` look i'm in complete agreement, 4.4 is like 3 months behind at this point and it's frustrating, but as I change things in baritone it breaks compatibility with things Impact used, which is why the `impact4.4-compat` branch exists in the first place. I'll obviously still backport needed fixes, but I can't really do new features =/

its up to bread man
