### ISSUE TITLE
baritone not following entity (side note: it also wont path a 45 angle anymore for some reason. ty cheers

### ISSUE THREAD

**Issue by majorkush** [cabaletta/baritone#2921]
I've attached the log file.
[latest.log](https://github.com/cabaletta/baritone/files/6946368/latest.log)

**Comment by ZacSharp** [comment]
Why didn't you fill in the template?
I can only assume that your Baritone is at least older than 1.2.15, which would mean that follow just does not work with Forge because #1971 wasn't merged yet when your build was made.
I have no idea why it should stop walking diagonally but there is a lot of optifine related exceptions so I'd suggest removing optifine (you should use as few mods as possible anyways when creating a bug report).
