### ISSUE TITLE
Add support for minecraft animals and mobs

### ISSUE THREAD

**Issue by kooldamian28** [cabaletta/baritone#2946]
## Describe your suggestion
A nice feature would be to make Baritone able to "mine" Minecraft mobs and animals, `#mine chicken` should kill a chicken and pick up the drop

## Settings
`#mine chicken` or any other relevant command should be fine

## Context
Having Baritone do that would be great!, because apparently, going around finding animals is pretty tough to do especially in 2b2t

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by FloGo3308** [comment]
1. This will prob never be in baritone because baritone is a pathfinding bot, not a hack, neither a murder machine.
2. "mine" mobs? Just call it killing/attacking
3. If you really want this, just do ``#follow entity pig`` to find and follow pigs(or other mobs if you like) and use killaura from another mod

**Comment by kooldamian28** [comment]
Good idea! Thanks!
