### ISSUE TITLE
Baritone doesn't mine

### ISSUE THREAD

**Issue by megamind81** [cabaletta/baritone#2989]
hello everyone, i wanted to mine ore from ic2, text "#mine ic2:resource:1".  Baritone can see these ores, but dont mine them. And chat is full of "Pathing exeption: java.lang.NullPointerExeption", what should i do? (sry for bad english)

**Comment by scorbett123** [comment]
Please fill out the issue template properly.

 Choose the appropriate one and fill out the requested information, your issue is a bug
 
 * [**Bug**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=bug&template=bug.md)
 * [**Suggestion**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=enhancement&template=suggestion.md)
 * [**Question**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=question&template=question.md)
