### ISSUE TITLE
Baritone is unresponsive

### ISSUE THREAD

**Issue by veccyboi** [cabaletta/baritone#3038]
Minecraft version: 1.16.5
Baritone version: standalone forge 1.6.3
Other mods (if used): this is my mods folder: 
![image](https://user-images.githubusercontent.com/85643556/137610254-d1f2b1de-3362-498b-a402-4cf475070cc1.png)

Whenever I type in a command, baritone will show the highlights and stuff, but not move

**Comment by SteamDoge9000** [comment]
This is a duplicate, Ik cus I had the issue, the issue is with Immersive portals, the mod alters the portal structure and for some reason causes the movement to fail because of it, @wagyourtail has made a fix to this in their fork of it and the build can be located in the actions menu of thier raspatory

**Comment by ZacSharp** [comment]
I'll just assume that's the issue. Huge modpacks are just annoying.

**Comment by SteamDoge9000** [comment]
it IS the issue
I know because thats what was casuing it
