### ISSUE TITLE
I want baritone to break bedrock

### ISSUE THREAD

**Issue by SuperIsakSwahn** [cabaletta/baritone#3078]
## What do you need help with?
With as much detail as possible, describe your question and what you may need help with.
I am trying to play a terminator challenge (From Dreams minecraft) but the plugin for the terminator has so many issues that it literally puts you on top of bedrock somehow, and i got another plugin that allows you to break bedrock, but baritone doesn't try to break it at all. So how do i make it start breaking the bedrock?
## Final checklist
- [v] I know how to properly use check boxes 
- [Just use ctrl+f to look for it] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
You would need a costom build that special cases bedrock to be considered breakable despite the block properties declaring it to be unbreakable.
Since you only want this for the builder you can probably get away with just changing the builder scan function, but I haven't looked into it so don't just take this as a fact.

**Comment by SuperIsakSwahn** [comment]
If you close this im just gonna open a new one lol

**Comment by SuperIsakSwahn** [comment]
Actually nah impact is probably better

**Comment by ZacSharp** [comment]
If you want a more detailed answer you should just reply here instead of annoying everyone with duplicate issues.
I don't write multiple pages of text for every generic question just to be sure I covered every possible more concrete question, because that's simply too much and chances are you understand nothing of it because you have never worked with code (and what I know about you so far makes me think that totally is the case).

Also Impact does not (or at least should not) change Baritones internal behaviours, so it is not the right place to ask this question, especially if you mean https://github.com/impact/impact/issues/112.
Did you even look at the repo before opening the issue?
You asked a Minecraft/Baritone related question in the repo of a package manager for a physics simulation modelling language.

**Comment by scorbett123** [comment]
wait lol, what must the owners of that repo be thinking seeing that written as an issue for them
