### ISSUE TITLE
various tweaks to scematic mode

### ISSUE THREAD

**Issue by himanss** [cabaletta/baritone#3083]
## if the setting "place literal blocks" is turned off, I propose the following changes should occur.

- if baritone is told to place a farmland block, it will instead place a dirt block and use a hoe on it.
- if baritone is told to place a water source block, it will use a water bucket.
- if baritone is told to place a flowing water block, it will be ignored.
- if baritone is told to place crops, it will place the seeds for that item.
- if baritone is told to place a structure void, it will not replace the original block

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
* You can add `farmland->dirt` or `farmland->farmland,dirt` to `buildSubstitutes` to allow it to place dirt instead. Using a hoe on has only been suggested for `#farm` so far (#827), but this issue is a bit cluttered with other stuff so please open a new one just for that feature.
* Not possible, but  #477 already exists so you don't need to open a new issue for it.
* You can add `water` to `buildSkipBlocks` to ingore *any* water (no specific blockstates sadly) and only ignoring flowing water should probably be handled when changing the general handling for water, so no issue on this one please
* Not possible, please open a separate issue on this as well 
* Just add `structure_void` to `buildSkipBlocks`
