### ISSUE TITLE
why does my minecraft crah when i try to do anything in the overworld with barithone?

### ISSUE THREAD

**Issue by iraklidzaganishvili** [cabaletta/baritone#3094]
Hello recently when i tried to use baritone for anything that requires pathfinding in the overworld(for example #goto or #mine) it just freezes my minecraft and says that minecraft is out of memory, or just crashes it if i give it too much RAM.
In the nether, everything works fine even when i gave mc only 2 gigabytes of RAM.
I use impact with baritone so is that why it does that? also it used to work several days ago so i don't know what happened. on my other mc account and in a survival world it works. does it not like the terrain?(because coordinates where the only difference in the account test)

edit: i also checked in a different spot on the map it doesn't crash anymore. why does it crash at my base then? 

thank you for  reading.

**Comment by ZacSharp** [comment]
Short answer: idk.
Long answer: I have no idea and it is unlikely others will know, because you provided so little information. The least I need to have a guess at what causes a crash is the log containing the crash and unless it is a trivial problem I need to be able to reproduce the crash myself. Because of that last point I also don't think the chances of this bug being fixed are high, because such obscure bugs as "it crashes only at that position in that world and nowhere else" can usually not be reproduced and are not simple enough to be fixable from just a crashreport.

**Comment by monsters-97** [comment]
I have a similar problem. Here is my crash repor
[crash-2021-11-19_22.24.59-client.txt](https://github.com/cabaletta/baritone/files/7571052/crash-2021-11-19_22.24.59-client.txt)
t

**Comment by ZacSharp** [comment]
@monsters-97 I'd be surprised if your crash is locational or related to this one in any way other than by both being a crash.

**Comment by ejsupernova** [comment]
Try opening the output log and telling us the error msg

**Comment by wagyourtail** [comment]
closed for inactive. post a log or something and we might open it back up

**Comment by ejsupernova** [comment]
Me?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by wagyourtail** [comment]
No, the guy who created this issue and its crashing for. Unless you're able to reproduce this and post a crash log. You posted asking for output log; they didnt post after a while -> closed for not enough information
