### ISSUE TITLE
Baritone forge crashing with RandomPatches

### ISSUE THREAD

**Issue by AghoyPandaaa** [cabaletta/baritone#3095]
## Some information
Operating system: win10
Java version: 16
Minecraft version: 1.12.2
Baritone version: 1.2.15 forge api
Other mods (if used): Life in the village 1 modpack + RandomPatches ( an important part of mod pack )

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
install baritone with life in the village modpack 
or install baritone with randompatches mod only ( version :  1.22.7-10)
the game crashesh 10sec after you hit play button
## Modified settings
To get the modified settings run `#modified` in game
[logs.zip](https://github.com/cabaletta/baritone/files/7571677/logs.zip)

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
The problem is RandomPatches causing `net.minecraft.client.gui.GuiScreen` to be loaded before Mixin can transform it. For order related things you can always try to change the order mods are loaded in by renaming the jars but I doubt that will help here. Since I found no usage of said class in RandomPatches 1.22.1-10 I'd suggest you try turning off `fastLanguageSwitch` and `patchTitleScreenOnDisconnect` in the RandomPatches config and if that doesn't help my last guess would be turning off all patches and the reenabling them to see which one causes the crash (hoping there is one you can turn off to fix it).

**Comment by AghoyPandaaa** [comment]
Thank you for your help

the solve is to just disable all client sided settings and go in the game with baritone or impact

when ur game is loaded to main menu U can go and reset all client sided settings of random patchs to default
and works correctly

the only problem is to disable those settings every time you want to close the game

Thanks Again ♥
