### ISSUE TITLE
Baritone does not see all ores

### ISSUE THREAD

**Issue by Tassf** [cabaletta/baritone#3144]
(Sorry, I translate via google)
In the MineProcess.java file, I found the ORE_LOCATIONS_COUNT constant. I have a problem AllowOnlyExsposedOres does not find ALL ores. Having flown to freecame, he noticed that he did not see in distant chunks. Can you somehow increase the scanning distance without rewriting the mod?

**Comment by ZacSharp** [comment]
For performance reason Baritone discards all but the closest 64 ore locations. Usually that means it will consider the farther away ores once it has mined the closer ones, but due to how `allowOnlyExposedOress`, the unreachable blacklist and pruning implausible ores work it can happen that the closest 64 ores are all invalid, in which case Baritone will fail.

If that's a problem for you, you have to compile Baritone yourself with `ORE_LOCATIONS_COUNT` set to a higher value.
EDIT: `ORE_LOCATIONS_COUNT` has been replaced by the `mineMaxOreLocationsCount` setting.
