### ISSUE TITLE
What does this error message mean?

### ISSUE THREAD

**Issue by JoeySuper1** [cabaletta/baritone#3160]
## What do you need help with?
I was trying to build a schematic with the #build command and an error message popped up, it said exactly this:

Successfully loaded schematic for building
Origin: BetterBlockPos{x=1485,y=-60,z=891}
Missing materials for at least:
6x null
Unable to do it. Pausing. resume to resume, cancel to cancel

The only part I am confused about is when it says "Missing materials for at least: 6x null".
I have all the materials and resuming makes the relatively same message appear.

Extra Information:

Baritone: Baritone Fabric 1.18
Fabric Version: 0.12.12-1.18.1
Fabric API Version: 0.44.0+ 1.18

## Final checklist

- [x]  I know how to properly use check boxes 

- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
That message means you have stumpled on just another problem the builder has, caused by positions outside the schematic ending up on the list of incorrect positions and then being checked for material availability. Canceling and restarting the build should fix it.

Are you using a schematic file (without `buildSkipBlocks`) or `#sel replace/shell/walls`/a schematic with `buildSkipBlocks`? For the latter (non-box shaped schematics) I know a possible cause, for the former I don't.
