### ISSUE TITLE
follow command not working

### ISSUE THREAD

**Issue by Shubu909** [cabaletta/baritone#3161]
## Some information
Operating system:
Java version:
Minecraft version:
Baritone version:
Other mods (if used): 

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ ] I have included logs, exceptions and / or steps to reproduce the issue.
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
Can you maybe provide more information? I'm especially interested in what you did to make error happen and the error output you got from it (the log file).

Since you provided none of them, let me have a guess.
* You used `#follow player <name>` where `<name>` refers to a player outside render distance
* Chat told you about an unreported exception and the log contains a NullPointerException from baritone.* classes

If that's the case then try following a player in render distance, if I'm wrong then please provide the information requested by the issue template.

**Comment by Shubu909** [comment]
Hey @ZacSharp how are you doing, can you tell how much is the radius and etc that disables it?

**Comment by Shubu909** [comment]
or is it ok if i can describe you this issue in discord cuz its kind of tough to message through here

**Comment by Shubu909** [comment]
> 

but can we use this for hide and seek with friends though me and my friend on my smp were doing a mansion raid together but at that time it worked perfectly fine but during hide and seek i though to use this command then yes and error came up so i reported this here as mentioned in the chat message of mc.

**Comment by ZacSharp** [comment]
Have a look at render distance and simulation distance [here](https://minecraft.fandom.com/wiki/Options#Video_Settings). If you are on a mc version older than 1.18 they are both the same value and called render distance. Also note that the *server side* value of the setting is important, not the client side value.
If you are on 1.18 (or newer) I'm not sure which is the one you have to look at here.

Also I don't use discord.
