### ISSUE TITLE
help configuration of legitmine

### ISSUE THREAD

**Issue by lingyunQAQ** [cabaletta/baritone#3207]
Hey, would anyone like to share the efficient configuration of legitmine
Or tell me what it needs to be configured

**Comment by ZacSharp** [comment]
Turning on legitmine is really just the `legitMine` setting and the rest is mostly the same as for normal mining.
Settings exclusive to legit mine are
* `legitMineYLevel`
* `legitMineIncludeDiagonals`

And settings shared with normal mining are
* `blacklistClosestOnFailure`
*  `mineGoalUpdateInterval`
* `allowOnlyExposedOres` (should not have an effect with legit mine on because visible ores should always be exposed)
* `allowOnlyExposedOresDistance` (same as above)
* `mineScanDroppedItems`
* `mineDropLoiterDurationMSThanksLouca`
* `forceInternalMining`
* `internalMiningAirException`
* `useSwordToMine`
* `notificationOnMineFail`
* `minYLevelWhileMining`

And these only work with legit mine off
* `extendCacheOnThreshold` because legit mine doesn't scan at all
* `exploreForBlocks` because legit mine always explores

And while those are a lot of settings (plus potentially a few I missed) you probably don't need to change them. I think the most interesting ones are
* `mineGoalUpdateInterval` in case the scanning causes too much CPU usage
* `legitMineYLevel` to prefer mining on the y level your target ore is most likely to appear on
