### ISSUE TITLE
Setting up project on 1.18

### ISSUE THREAD

**Issue by PseudonymPatel** [cabaletta/baritone#3208]
## What do you need help with?
Hi, just had a couple clarification questions with getting started with development for the 1.18.1 version. I have some basic knowledge of forge as I have done a good chunk of modding on 1.7.10 and 1.12.2 forge modding.
1. The master branch is what is being used for developement of 1.18.1 version? or wagyourtail's 1.18.1 branch?
2. How do I compile for fabric vs forge? Is this handled in the gradle build system?

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by wagyourtail** [comment]
1. my 1.18 branch, or the 1.18 branch here if it ever actually gets merged.
2. `gradle build -Pbaritone.fabric_build` / `gradle build -Pbaritone.forge_build`, have to add the extra properties manually or it'll build for the client.json/launchtweaker env.

the 1.17+ gradle build scripts are (essentially) fabric build scripts as they use architectury loom in order to make the buildscript not look completely horrible like in 1.16
