### ISSUE TITLE
RunClient failing because of baritone integration

### ISSUE THREAD

**Issue by wallhacks0** [cabaletta/baritone#3233]
I am trying to add baritone to my client and have it compile in to the actual jar. I got this all working and running but my run Client task is now no longer functioning. When attempting to run I get a strange error that almost explains nothing, I tested the current state of the grade without baritone added to the repos and it ran the client perfectly.
[my client](https://github.com/wallhacks0/Spark-Client/tree/baritone/gradleupdate )
[log](https://github.com/cabaletta/baritone/files/7967045/log.txt)

**Comment by ZacSharp** [comment]
I'd suggest having a look at other projects using Baritone. I personally don't know too much about it and so for (with two eceptions) I've just written my code directly into Baritone to avoid those problems.
For my last attempt I managed to get a srg mapped jar from Baritone which then loaded without issues in both development and production enviroments (in the former I had to explicitly tell Forge about the MixinTweaker) but it seems like the solution used by most projects works without special jars. I think you have to disable the refmap and maybe a bit more, it's been quite a while since I used that attempt the last time.

**Comment by wallhacks0** [comment]
I looked at all clients i know have baritone but for most of them the runclient task wasnt working too. Would it be allowed to have the actual baritone source in my source so I dont have to deal with gradle on that part?

**Comment by ZacSharp** [comment]
Your project doesn't have a license that means "All rights reserved" and as such you are not allowed to copy any part of Baritone into your project (using it as a dependency is still allowed). I think you may only copy it if your project has a LGPL or GPL compatible license, but you should ask someone else than me about this. (Also the readme says you copied from other clients, are you sure their licenses allow you to do so?)
