### ISSUE TITLE
Please add a brief but descriptive title

### ISSUE THREAD

**Issue by PhlegethonAcheron** [cabaletta/baritone#3288]
## Describe your suggestion
It would be absolutely amazing if baritone did not think that it could walk on redstone torches, or torches in general. Because you can't. 

## Context
It would prevent baritone creating an impossible path, as well as getting stuck in a break torch, place torch loop.

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
I never saw Baritone planning to walk on a torch or anything else you can't walk on, except when using the builder (#3142).
Since you said you want to prevent a place-break loop I'll just assume you are using the builder and close this as a duplicate, please let me know in case that assumption was wrong.
