### ISSUE TITLE
An unhandled exception occurred while trying to run mine command

### ISSUE THREAD

**Issue by MoonRadar336** [cabaletta/baritone#3323]
## Some information
Operating system: Windows 10 64 bit
Java version: ?
Minecraft version: 1.18
Baritone version: 1.8.3
Other mods (if used): Forge

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`
[latest.log](https://github.com/cabaletta/baritone/files/8247673/latest.log)
Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Just try to run mine command to diamonds.

## Modified settings
To get the modified settings run `#modified` in game
All modified settings are just two dashes.
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
This is probably due to an incompatibility whilst upgrading to minecraft 1.18.2, if you are playing 1.18.1, or 1.18 please use baritone version 1.8.2, for 1.18.3 use baritone version 1.8.3.

If you are using the correct version please attach the debug.log as this contains some more useful information.
