### ISSUE TITLE
won't mine lit_redstone_ore

### ISSUE THREAD

**Issue by cornernote** [cabaletta/baritone#3353]
## Some information
Operating system: windows
Java version: 
Minecraft version: 1.18.2
Baritone version: 1.18.3
Other mods (if used): 

## Exception, error or logs
[22:02:30] [Render thread/INFO]: [CHAT] [Baritone] > mine lit_redstone_ore
[22:02:30] [Render thread/INFO]: [CHAT] [Baritone] Error at argument #1: Expected z

## How to reproduce

Simply type `mine lit_redstone_ore`

## Modified settings

```
legitMine = true
```

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
According to the [wiki](https://minecraft.fandom.com/wiki/Redstone_Ore#History) they merged `lit_redstone_ore` into `redstone_ore` five major version ago.
This also means that Baritone can't distinguish between them on any version after 1.12.2 (because that's the latest version where they are separate blocks)

**Comment by cornernote** [comment]
I see.

`#help mine` gives `lit_redstone_ore` as an example argument for the command.

**Comment by ZacSharp** [comment]
Thanks for bringing this to our attention.
There was actually more changes that the help text missed (see #3357).
