### ISSUE TITLE
Baritone wont avoid mobs when pathing even with avoidance = true

### ISSUE THREAD

**Issue by TheCogster409** [cabaletta/baritone#3382]
## Some information
Operating system: Windows 11
Java version: idk 1.8 i think
Minecraft version: 1.18.2
Baritone version: Latest
Other mods (if used): Fabric mods are: tweakeroo and wurst. No forge mods

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here. idk just pathfind through mobs with avoidance = true

## Modified settings
[debug.log](https://github.com/cabaletta/baritone/files/8443347/debug.log)
[latest.log](https://github.com/cabaletta/baritone/files/8443348/latest.log)

To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ ] I have included logs, exceptions and / or steps to reproduce the issue.
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by TheCogster409** [comment]
ok thanks
i was trying to escape 2b2t spawn but i kept running into withers

**Comment by DexMill** [comment]
How high does it need to be for it to totaly avoid mobs mine is set to 100 and is still dying to mobs while mining

**Comment by PurpBatBoi** [comment]
> Avoidance doesn't mean that all mobs are avoided, it just means that baritone will preferably pick paths with no mobs, instead of paths with mods. To increase the amount it disliked paths which go near mobs increase the mobAvoidanceCoefficient setting

not to re-open the issue but would be nice if the path dynamically adjusted in realtime itself to avoid hostile mobs if they happen to spawn or just happen to get very close to you

**Comment by bphd** [comment]
Exacly, that's the problem. When the path is established, it will follow it without questioning it whatsoever. Whatever if monsters have spanwed or moved in the path. It will update the path if a new chunk has appeared, if a goal was reached, things like that. And upon that he will now consider new mobs. But thats not avoidance, avoidance should happen at all time, in real time like you say. There is probably a variable to stress out path updating. But I rather talk about even that trigger events than pure time elapsed since last update. Because it's not about time, mob don't wait 5 seconds or 5 minutes or whatever. It's a real time work, maybe the right trigger would be mob apparition or mob movement, but it happens at each tick. Idk if @leijurv have a smart idea
