### ISSUE TITLE
Baritone auto mining for needed materials once inventory is empty.

### ISSUE THREAD

**Issue by Patutya** [cabaletta/baritone#3385]
## Describe your suggestion
After using up every available material in your inventory baritone would go off and mine for needed ones. And return to the discontinued build position.

## Settings
It probably should be a boolean setting. That would toggle mining option

## Context
It would be a huge help for all the survival users with huge builds

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have used build and mine commands

**Comment by Mathrandom7910** [comment]
this would likely be better for altocleft https://github.com/gaucho-matrero/altoclef

**Comment by ZacSharp** [comment]
1. Altoclef has the prerequisites, but that doesn't mean Baritone can't get this feature as well
2. However that's unlikely because you would first have to implement e.g. #2597 to stop `#mine` from taking the blocks from your schematic *and* you would need a lot of changes to how processes interact with each other (they can only cancel eachother atm) so `BuilderProcess` can temporarily delegate to `MineProcess`

**Comment by Patutya** [comment]
how about we just make a sel where it can mine for needed materials

**Comment by ZacSharp** [comment]
It would require roughly the same internal changes so it doesn't really matter.
The big problem is cooperation between processes anyways.

**Comment by Mathrandom7910** [comment]
more issues can occur if you require an item such as endstone as you're in overworld
