### ISSUE TITLE
How to Build a Litematic Without All The Materials Required?

### ISSUE THREAD

**Issue by uhshafi** [cabaletta/baritone#3397]
So I'm trying to build a Litematica file and it is a huge build. I tried doing #build Sky Island House.litematic and it will just say, "Error at argument #3: Expected RelativeBlockPos" meaning that I probably don't have enough materials. But it's such a big build, how am I supposed to build something but with just some of the materials? Like maybe I have all the stone or something, can't it just build all the stone, then get the other material, then build it from that, etc?

**Comment by pikachu1298** [comment]
ya cant

**Comment by ZacSharp** [comment]
The error message tells you that it expected the 3rd argument to be a position but the actual problem is that your schematic name contains spaces (" ") and thus is split into multiple arguments. You will have to rename the schematic to not have spaces in its name and unless you are using #2544 or my for of it you will also have to convert the `*.litematic` to a `*.schematic` or `*.schem`.
Also you sadly can't really build schematics material by material because Baritone fails if there are wrong blocks nearby it can't fix rather than walking away and working on other parts of the build first.
