### ISSUE TITLE
Doesn't mine went typed #mine oak_log

### ISSUE THREAD

**Issue by jianwwae** [cabaletta/baritone#3405]
When i type #mine oak_log or #mine iron_ore it doesnt mine them

**Comment by ZacSharp** [comment]
I can't really help you based on the information you provided.
My best guess is that you are using the wrong version of Baritone (see pinned issue) because that's the most frequently reqported "bug" currently.
If that's not your problem you'll have to fill in the information requested by the template you deleted.

**Comment by jianwwae** [comment]
Thank you for the information IT REALLYYYY helped🙂🙂. I didnt know i was
using the wrong version.
