### ISSUE TITLE
Bug: Auto placing does not work when auto mining if fast place is enabled

### ISSUE THREAD

**Issue by jakester620** [cabaletta/baritone#343]
https://www.youtube.com/watch?v=mmsO8Z2osGM&feature=youtu.be
If fast place is enabled when auto mining, the auto place feature does not function. You can get stuck in a 2 deep bedrock hole and you are stuck jumping up and down facing down like you are going to place a block until you disable fast place.

**Comment by leijurv** [comment]
Impact's fast place is apparently not compatible with Baritone's method of right clicking. 

Sorry, I know it was me that directed you here in the first place, but this can't be fixed from Baritone's side (since Impact is closed source), so could you re-file it under https://github.com/impactDevelopment/impactclient/issues thanks =)
