### ISSUE TITLE
buildskipblock cannot found in baritone 1.16.5

### ISSUE THREAD

**Issue by mieucun123** [cabaletta/baritone#3469]
## What do you need help with?
i can't find command buildskipblock in baritone 1.16.5

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
That's because the latest release was made after #2526 was merged. If you want to use `buildSkipBlocks` you will have to build Baritone yourself because when #2526 was merged there was no automatic CI build.

**Comment by wagyourtail** [comment]
> because when https://github.com/cabaletta/baritone/pull/2526 was merged there was no automatic CI build.

but there are later builds in the CI, so, one of those can be used.

**Comment by ZacSharp** [comment]
Oh right, only looked at the pr itself...

I'd suggest downloading the artifacts from [this run](https://github.com/cabaletta/baritone/actions/runs/2380428705) because it includes a fix for `#build` being run while Baritone is already building. If you want an official version download the artifacts of the the newest run on [this list](https://github.com/cabaletta/baritone/actions/workflows/gradle_build.yml?query=branch%3A1.16.5+is%3Asuccess+actor%3Aleijurv)
