### ISSUE TITLE
How long will it take to use Baritone 1.19?

### ISSUE THREAD

**Issue by XYEXEcom** [cabaletta/baritone#3507]
How long will it take to use Baritone 1.19?

**Comment by ZacSharp** [comment]
I'm heavily tempted to just answer the question you asked instead of the one you wanted to ask. Seriously what is so difficult about a. being a little more patient and b. searching whether the desired information is already available. People are spamming issues with update requests every single release.

Baritone 1.19 will release when all builds are ready for release and currently we are waiting for archloom to properly support vanilla remapping.

**Comment by wagyourtail** [comment]
> currently we are waiting for archloom to properly support vanilla remapping.

which is waiting on upstream to fix it before I can tell shedaniel archloom is more broken
