### ISSUE TITLE
crash upon launch

### ISSUE THREAD

**Issue by Jaws6751** [cabaletta/baritone#3648]
## What do you need help with?
Is it possible to tell which mod Baritone has issues with through the log? I'm playing a modpack that works fine on its own, but when i add Baritone to it, it crashes with exit code 1. I also launched minecraft with just baritone and it launched and worked fine.
Minecraft 1.12.2
Forge 14.23.5.2860

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
If you know how to read the log file you can search it for a hint. However I don't think you'd had asked this question if you already knew the answer so I suggest you try removing all mods that are not required for the crash to happen and the remaining mod(s) is(are) the culprit.

Also if there's no reason to not do so you could also upload the log here so others can have a look at it.

**Comment by Jaws6751** [comment]
[latest.log](https://github.com/cabaletta/baritone/files/9502728/latest.log)
Heres the latest log from when I had Baritone added. Appreciate the response, but as the mod pack has 135 mods, I would rather find an easier way of figuring it out than spending over an hour finding the clashing mod(s).

**Comment by ZacSharp** [comment]
Definitely a mixin problem. I'd guess it's either RandomPatches, MixinBooter or LoliASM.
MixinBooter and RandomPatches are known to cause problems with Baritone (and the exception comes from RandomPatches).

If none of those three makes a difference you can always remove half of your modpack to quickly narrow down the mods that could cause this (ceil(log2(135)) = 8 tests instead of 135 tests)

**Comment by Jaws6751** [comment]
Thanks for the info
