### ISSUE TITLE
How to get started with personalizing baritone and creating custom scripts?

### ISSUE THREAD

**Issue by TheContainer** [cabaletta/baritone#3666]
## What do you need help with?
Hey there,
I already have experience with programming, just with Python and a bit also Java. On YouTube I have seen how baritone plays through the game. I wanted to know where I can start to personalize baritone also like that.

## Final checklist
- [ ] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue (except here).

**Comment by ZacSharp** [comment]
If chat control is enough you can use any macro mod, otherwise you'll need something that can call arbitrary Java methods.
Macro mods capable of this are [AdvancedMacros](https://www.curseforge.com/minecraft/mc-mods/advanced-macros) (Lua) and [JsMacros](https://www.curseforge.com/minecraft/mc-mods/jsmacros) (JavaScript by default), which also both provide wrappers for the most commonly used Minecraft classes so you probably won't run into obfuscated classes. If you use JsMacros you can also use [Python, Lua, Ruby, Groovy or Kotlin](https://jsmacros.wagyourtail.xyz/?/extensions.html) for scripting.

If the macro mods are not powerful enough (e.g. you need a class they don't wrap) you can write a mod using Baritone as a dependency, but I wouldn't suggest you to do this if you've never written a mod so far (there's some difficulties with getting Baritone to cooperate).
It's probably better if you modify Baritone itself instead. For that there's a rudimentary setup guide [here](https://github.com/cabaletta/baritone/blob/master/SETUP.md#build-it-yourself). If you tell me which version you want to use I can also provide more detailed instructions on how to (modify and) build Baritone yourself.
