### ISSUE TITLE
Can't #build noteblocks

### ISSUE THREAD

**Issue by Flix3ris** [cabaletta/baritone#3712]
#build does not work with noteblocks with a changed note.

**Comment by ZacSharp** [comment]
That's because you can't place noteblocks with a note other than the default note.
I'd say this is not a bug but a missing feature (handling blocks that have to be placed in a wrong state before correcting them).

For future readers: if you already have the `buildIgnoreProperties` setting you can use it as a workaround (as of writing this only 1.12.2 CI builds have the setting).
