### ISSUE TITLE
Baritone random walking + not stopping

### ISSUE THREAD

**Issue by AnonymosProggramer** [cabaletta/baritone#3713]
## Some information
Operating system: Windows 10 
Java version: 8 
Minecraft version: 1.12.2
Baritone version:1.2.4
Other mods (if used): None
Cheat Clients: Lamda, Rusherhack

## Exception, error, or logs
[2022-11-01-6.log](https://github.com/cabaletta/baritone/files/9941098/2022-11-01-6.log)

## How to reproduce
Not sure.

## Modified settings
There are none.

## Context

When I launch Lamda with Baritone. The baritone starts to randomly walk on some random points I tried #stop; #cancel and pause. When I say pause it just starts randomly moving on the screen.Most of the commands don't work.I will post the video here

https://user-images.githubusercontent.com/96958431/200063970-d76be152-d917-4369-8ebb-e4d98acf5558.mp4

## Final checklist
- [x] I know how to properly use checkboxes 
- [x] I have included the version of Minecraft I'm running, baritone's version, and forge mods (if used).
- [x] I have included logs, exceptions, and/or steps to reproduce the issue.
- [x] I have not used any OwOs or UwU's in this

**Comment by ZacSharp** [comment]
I'd guess that one of your clients is restarting Baritone, maybe this is https://github.com/lambda-client/lambda/issues/347.
Also I'd be interested in whether this happens without Rusherhack (since you said it's with Lambda) and what `#proc` outputs.

Btw if you actually care about your desktop being blurred in the recording you should do that manually. Flixier missed a couple frames.

**Comment by AnonymosProggramer** [comment]
@ZacSharp So when I disabled Rusher hack it doesn't stop. 
![Proc](https://user-images.githubusercontent.com/96958431/200112016-822f6be2-8163-4b42-a474-108dda2b82f3.png)
This is my Proc.

**Comment by AnonymosProggramer** [comment]
@ZacSharp I fixed it by resetting config
