### ISSUE TITLE
move penalty

### ISSUE THREAD

**Issue by UltraBlackLinux** [cabaletta/baritone#3716]
## Describe your suggestion
Add a move penalty so baritone avoids walking when possible

## Settings
movePenalty

## Context
These garbage prison servers sometimes have regenerating blocks like on Hypixel skyblock. It seems more efficient to just rotate the player instead of walking and readjusting everytime a block is mined.

This could also assist with stone generators, meaning that baritone actually only mines the generated blocks and not the other ones

I general, I think baritone should rather turn the camera instead of walk to make many mining processes much more efficient

Edit: [Video](https://chonkyrabbit.eu/filebin/r/5rVXox1PdY#806az2q4hF3SgmRn41eN2OIWJaPTdQK2smIQiqL7sH4=)

**Comment by offbeat-stuff** [comment]
there are settings you can change in baritone to adjust different penalties

**Comment by UltraBlackLinux** [comment]
I haven't seen a move penalty though

**Comment by ZacSharp** [comment]
It wouldn't be of any use to you. It would slow down pathing by making the search more Djikstra-like and Baritone would still walk towards the nearest ore on the shortest path because there's no better alternative no matter how high it thinks the cost is. (if you set an overly high penalty it would stall instead because there's no path with less than COST_INF cost)

**Comment by UltraBlackLinux** [comment]
right. I might need to create a new issue then.
