### ISSUE TITLE
How to compile & use bot-system branch?

### ISSUE THREAD

**Issue by wellsilver** [cabaletta/baritone#3736]
## What do you need help with?
With as much detail as possible, describe your question and what you may need help with.

I tried just running gradle like the readme says, but it errors out

```FAILURE: Build failed with an exception.

* Where:
Build file '/workspaces/baritone/buildSrc/build.gradle' line: 23

* What went wrong:
A problem occurred evaluating project ':buildSrc'.
> Could not find method compile() for arguments [{group=com.google.code.gson, name=gson, version=2.8.5}] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 800ms
```

and also, the readme.md has no references to any kind of help using it even if building worked first time

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
That part works for me so I can only guess, with my only guess being that you are using an incompatible local gradle install instead of the wrapper script.
In case you get it to work you also want to make sure your default java version (the one invoked by plain `java`) is java 8, because `ProguardTask` might crash otherwise (does so with my j17 setup, fixed on master but bot-system is old and unmaintained).

If you have somehow worked around all the problems you will find the compiled jars in `<repo root>/dist` and to use it you can either use the forge jars as a regular Forge mod (won't show up on the mods list) or you make a custom version json for the launcher to use one of the other jars as a tweaker.

**Comment by wellsilver** [comment]
It randomly worked when I tried --stacktrace but doesnt work any other way. Lol
