### ISSUE TITLE
Mine command not working on spigot 1.19.3

### ISSUE THREAD

**Issue by Panabetic** [cabaletta/baritone#3756]
## Some information
Operating system: Mac OS X 11.6.7
Java version: unknown
Minecraft version: 1.19.3
Baritone version: null version
Other mods (if used): FabricAPT

## Exception, error or logs

[latest.log](https://github.com/cabaletta/baritone/files/10203033/latest.log)

## How to reproduce
Logged onto a server running spigot 1.19.3
opened baritone and ran .baritone mine diamond_ore
Received the following error: Caused by: java.lang.NullPointerException: Cannot invoke "baritone.api.cache.IWorldData.getCachedWorld()" because the return value of "baritone.api.utils.IPlayerContext.worldData()" is null

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by br0gio** [comment]
I'm also having this issue.

**Comment by wagyourtail** [comment]
can you update baritone and post new logs. I added a line to log if it's happening where I think, (if it is there, I have to fix the replaymod compat)

**Comment by FraserMcD** [comment]
> can you update baritone and post new logs. I added a line to log if it's happening where I think, (if it is there, I have to fix the replaymod compat because it would be breaking vanilla, if not it's something else)

Can u help me, having the same issue.

[latest.log](https://github.com/cabaletta/baritone/files/10224200/latest.log)

**Comment by wagyourtail** [comment]
> 
> Can u help me, having the same issue.
> 
> [latest.log](https://github.com/cabaletta/baritone/files/10224200/latest.log)

your baritone is not updated to the newest version, please update (grab unoptimized-fabric) and post new logs

**Comment by FraserMcD** [comment]
> e is not updated to the newest version, plea

where can I get that from?

**Comment by wagyourtail** [comment]
> https://github.com/cabaletta/baritone/actions/runs/3679500984

**Comment by F0xtastic** [comment]
I'm having this same issue, and I'm sorry to ask this, but where's the actual file to download on this page? 
https://github.com/cabaletta/baritone/actions/runs/3679500984

I'm genuinely doing my best but I don't see a download button or a link or whatever. Unless it's artifacts.zip and/or mappings.zip?

**Comment by rycbar0** [comment]
> I'm having this same issue, and I'm sorry to ask this, but where's the actual file to download on this page? https://github.com/cabaletta/baritone/actions/runs/3679500984
> 
> I'm genuinely doing my best but I don't see a download button or a link or whatever. Unless it's artifacts.zip and/or mappings.zip?

you need to be logged in in github and then you want to download the artifacts

**Comment by F0xtastic** [comment]
If I'm using Meteor, will I need to extract meteor and replace Baritone inside of that somehow? Or is this even possible for me to do by hand without in-depth knowledge of Meteor?

**Comment by wagyourtail** [comment]
just temporarily disable meteor (or you can remove baritone from the jars list inside fabric.mods.json and delete /meta-inf/jars/baritone)

**Comment by F0xtastic** [comment]
There wasn't actually anything baritone in /meta-inf/jars/baritone, but I did remove it from fabric.mods.json. Got this log for altered Meteor + Fabric unoptimized baritone: https://paste.ee/p/pHHux
Got this one for just baritone no Meteor: https://paste.ee/p/stSO9

Side note, the server I'm joining is Fabric 1.19.3. If I'm misreading this being the same issue then apologies!

**Comment by wagyourtail** [comment]
damn. It is what I thought... I'll look into a solution soon...

**Comment by DavidScann** [comment]
Would like to add that goto and farm also doesn't work. Crashes and gives identical error message.
(Sorry if it is obvious, I just wanted to say.)

**Comment by br0gio** [comment]
weird, goto does work for me

**Comment by MisterGrouch** [comment]
was having he same issue using meteor and outside of meteor as well

**Comment by Stupefiantt** [comment]
Hello, sorry bothering you,  (And sorry for my english)

I don't know if that can helping you, but i've the same bug, but i've found a way to fix it.

You need to go to the nether, and die by an monster (i've try by falling don't work) when you die that create an [Baritone] Death Waypoints and after that command work

**Comment by Crea-Slay** [comment]
i confirm what @Stupefiantt say. :)
Just need to die in the nether and it's work for me (no need to do the death waypoints)
But some command don't wokr (like schematica for exemple)

**Comment by Panabetic** [comment]
@Stupefiantt 's method works for me! The only annoyance is that you have to repeat the process every time you disconnect and reconnect to a server, but if you can get past that, its a workable method

**Comment by JoShMiQueL** [comment]
@Stupefiantt method does not work for me, it remains exactly the same

**Comment by Stupefiantt** [comment]
> @Stupefiantt method does not work for me, it remains exactly the same

Did you use the 1.19.3 baritone ?

**Comment by Stupefiantt** [comment]
> i confirm what @Stupefiantt say. :) Just need to die in the nether and it's work for me (no need to do the death waypoints) But some command don't wokr (like schematica for exemple)

Good to know i can help people, but the death waypoits is automatically creat for me

**Comment by JoShMiQueL** [comment]
> > @Stupefiantt method does not work for me, it remains exactly the same
> 
> Did you use the 1.19.3 baritone or the 1.8.3

Yes

**Comment by Enstrayed** [comment]
I am able to replicate this issue using the same setup as others (Meteor on 1.19.3). I wasn't able to test the workaround of going to the nether and dying.

The error `[03:45:28] [Render thread/INFO]: [STDERR]: Caused by: java.lang.NullPointerException: Cannot invoke "baritone.api.cache.IWorldData.getCachedWorld()" because the return value of "baritone.api.utils.IPlayerContext.worldData()" is null` made me think it was something to do with trying to run the mine command on a multiplayer server rather than single player locally. Testing this confirmed my suspicion as the repack command runs without an error and the mine command works as expected when running in single player locally.

**Comment by Enstrayed** [comment]
As a check I started a plain 1.19.3 Minecraft server on my PC and connected to it and attempted to run the repack and mine commands and got the same error as before. (I was previously testing on somebody else's server but they weren't using a stock server.)

If I were to hazard to guess, I assume something changed in 1.19.3 that caused `baritone.api.utils.IPlayerContext.worldData()` to not work anymore, or at least not in the way that it was coded. Whether this was intentional by Mojang or just a byproduct of some other change isn't something I could guess.

Just in case I saved my full client log but I doubt it'll show anything, since it seems to be the same as everyone else: https://downloads.enstrayed.com/Log_Files/baritone-3576_2022_12_19_log-client-1.txt (occurs at line 358)

**Comment by wagyourtail** [comment]
> As a check I started a plain 1.19.3 Minecraft server on my PC and connected to it

I tested with connecting to a local vanilla server as well, I was unable to reproduce with no mods, so I suspect it's either something wrong in fabricapi or meteor... I'll look into it a bit more today, make sure that's the case and report it as a bug to the appropriate location...

**Comment by wagyourtail** [comment]
ok. I've now managed to reproduce the issue in baritone. I have an idea for a fix... it's going to look a little ugly but get the job done

**Comment by wagyourtail** [comment]
I verified ^ working.

https://mclo.gs/4qNs5ZX (don't mind the opengl errors, that's the server's icon getting into a broken state)

**Comment by freshTsunami** [comment]
maybe i'm stupid but either baritone doesn't work despite the update or i didn't update baritone at all because i don't know which version i should put in the mod folder

## Some informations
Operating system: Windows 10
Java version: Version 8 Update 351
Minecraft version: 1.19.3 (fabric-loader-0.14.12-1.19.3/fabric/Fabric)
(I start Minecraft with a Curse Forge profile)

## Other Mods
AppleSkin
Architectury API (Fabric/Forge)
Cloth Config API (Fabric/Forge)
Fabric API
JourneyMap
Mod Menu
Replanting Crops (Fabric)
Roughly Enough Items Fabric/Forge (REI)
WI Zoom
WorldEdit
WorldEdit CUI (Fabric)
Distant Horizons:  A Level of Detail mod
Collective (Legacy Fabric)

## Log

[latest.log](https://github.com/cabaletta/baritone/files/10395077/latest.log)

**Comment by wagyourtail** [comment]
Update baritone, we're on 1.8.3-226

**Comment by freshTsunami** [comment]
How? I downloadet the artefacts.zip from https://github.com/cabaletta/baritone/actions/runs/3732468264

**Comment by JustKristy2002** [comment]
> I verified ^ working.
> 
> https://mclo.gs/4qNs5ZX (don't mind the opengl errors, that's the server's icon getting into a broken state)
> 
> Grab new version of baritone @ https://github.com/cabaletta/baritone/actions/runs/3732468264

can u give me a new updated verison for 1.19.3 since your file expired
