### ISSUE TITLE
How to place double chest in baritone

### ISSUE THREAD

**Issue by Tungdabiban2408** [cabaletta/baritone#3793]
## What do you need help with?
With as much detail as possible, describe your question and what you may need help with.

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
Sadly not possible because it requires either letting go of shift (which Baritone has to press to avoid opening GUIs) or detecting the need to click at the side of the other chest (there's no simple way to do that).

Basically anything that requires more than clicking with an item on the target position with any rotation is more than the builder can handle properly. It can place rotational blocks, but only if by chance it ends up walking to the correct side of the block.
