### ISSUE TITLE
Baritone tries to remove blocks it needs to place a block

### ISSUE THREAD

**Issue by Mackery6969** [cabaletta/baritone#3795]
## Some information
Operating system:Windows
Java version:18
Minecraft version:1.12.2
Baritone version:latest
Other mods (if used): none (i disabled them all)

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/A
[latest.log](https://github.com/cabaletta/baritone/files/10418751/latest.log)
pplication\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running
, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

when building a structure the bot is trying to place stone brick stairs but it needs to put a temporary block to put it on, when it tries to place that temporary block it breaks it because its not part of the build

**Comment by Mackery6969** [comment]
update: this only happens on some blocks (I don't know which ones but sea lanterns work and stone brick stairs don't)

**Comment by ZacSharp** [comment]
> update: this only happens on some blocks (I don't know which ones but sea lanterns work and stone brick stairs don't)

This might be because after Baritone placed the support block it can instantly place the sea lantern, but for the stairs it doesn't have the correct orientation and "gets time to think about other things".

This problem is already known, it's just so far nobody came up with a solution (that doesn't cause more problems).
You can try adding your scaffolding blocks to `buildIgnoreBlocks`, but that's not very practical either.
