### ISSUE TITLE
Unknown error trying to follow

### ISSUE THREAD

**Issue by Sussy-OS** [cabaletta/baritone#3811]
## Some information
Operating system: Windows 11
Java version: Recommended for 1.16.5
Minecraft version: 1.16.5, Cracked, playing on cracked server
Baritone version: 1.6.3 Fabric
Other mods (if used): Fabric API, Wurst

## Exception, error or logs
[2023-01-24-4.log](https://github.com/cabaletta/baritone/files/10492942/2023-01-24-4.log)

## How to reproduce
Go on server, run 
```
#follow player PLAYERNAME
```

## Modified settings
None

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by rycbar0** [comment]
i  would have to dig into the code to confirm or disprove this but it could be that baritone cant finde the player because he uses a cracked account and therefor his player is not properly registred.

**Comment by Sussy-OS** [comment]
Actually, probably, as he *does* use a cracked client as I do.

**Comment by ZacSharp** [comment]
Baritone can only follow players within you render distance as otherwise there is no way to tell where they are.
The unhandled exception is already replaced with a more informative message on newer builds (no release yet, only [CI builds](https://github.com/cabaletta/baritone/actions/workflows/gradle_build.yml?query=event%3Apush+is%3Asuccess+branch%3A1.16.5)).

BTW: Chat buttons don't work for you because Wurst breaks them.
