### ISSUE TITLE
beritone crash's with every untility client i use

### ISSUE THREAD

**Issue by DuckysClips** [cabaletta/baritone#3813]
## Some information
Operating system: windows 10
Java version:( idk )
Minecraft version:1.12.2 forge 14.233.5.2860
Baritone version:(idk, the one that came with the client)
Other mods (if used): cookie client
and lambda client

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`
[2023-01-26-3.log.gz](https://github.com/cabaletta/baritone/files/10513966/2023-01-26-3.log.gz)

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
try to use baritone
## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [ kinda] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ yes] I have included logs, exceptions and / or steps to reproduce the issue.
- [yes ] I have not used any OwO's or UwU's in this issue.

**Comment by DuckysClips** [comment]
i have tried with meteor and it does not work

**Comment by rycbar0** [comment]
[16:56:35] [Client thread/INFO] [FML]: Searching C:\Users\Grayson\AppData\Roaming\.minecraft\mods for mods
[16:56:35] [Client thread/ERROR] [FML]: Unable to read a class file correctly
java.lang.IllegalArgumentException: null

the error appears to originate in the Forg mod loader. pls make sure its installed correctly and try running it without any mods first. after that try to run it with only baritone.

**Comment by ZacSharp** [comment]
That's the lambda jar freaking out the mod file scanner and (probably) not the reason for the crash.

The actual crash comes after all those 70MB of gl errors from Baritone trying to initialize a hash map with an invalid load factor.
@DuckysClips can you maybe provide the contents of your Baritone settings file? I'd be especially interested in the value of `pathingMapLoadFactor` (it has to be between 0 and 1 for things to work).

**Comment by wagyourtail** [comment]
yeah. that exception is unrelated rycbar0

**Comment by DuckysClips** [comment]
[settings.txt](https://github.com/cabaletta/baritone/files/10514311/settings.txt)


>

**Comment by wagyourtail** [comment]
change the load factor setting to match with the error in that settings txt. 0.0 is not > 0.0

**Comment by ZacSharp** [comment]
Also you got a couple more settings set to questionable values.
* `blockReachDistance` has to be higher than ~2 for Baritone to not get stuck when trying to place blocks (if you want to disable placing use `àllowPlace` instead)
* setting `costHeuristic` to 0 forces Baritone to consider all paths shorter than the resulting path, even in simple terrain when walking straight is the shortest path. Unless you are trying to solve a maze this should be near (but below) the default value.
* `pathCutoffFactor` setting this higher makes Baritone reconsider the end of path segments, generally improving path quality because it doesn't commit to short trips into dead ends as easily.
* `mobSpawnerAvoidanceCoefficient` and `mobAvoidanceCoefficient`, setting these to zero has the same effect as disabling `avoidance` (disabled by default) but has worse performance.
* `pathingMapLoadFactor` this one is the only one you **have** to change. Baritone crashes if this setting is 0.
