### ISSUE TITLE
how can i download 1.19.3 baritone

### ISSUE THREAD

**Issue by vercito** [cabaletta/baritone#3816]
## Final checklist
- [x] I know how to properly use check boxes 
- [x ] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
The currently newest CI run is [this one](https://github.com/cabaletta/baritone/actions/runs/3914210910). To download it you have to be logged in to github and then click on "Artifacts" (the one in the list, not the header) at the bottom of the page.

Since that run is going to expire at some point, [here](https://github.com/cabaletta/baritone/actions/workflows/gradle_build.yml?query=event%3Apush+is%3Asuccess+branch%3A1.19.3) is a link to the list of CI builds with filters set to only show successful builds on the 1.19.3 branch. Select the top entry and then proceed as explained above.
