### ISSUE TITLE
Extend path search

### ISSUE THREAD

**Issue by 1Euro7Cent** [cabaletta/baritone#3915]
## What do you need help with?
I have a lot of tunnels and baritone is just searching for the nearest tunnel and breaking blocks when there is a tunnel a few blocks in a different direction that path is much shorter and doesn't require block breaking.

I already increased block break penalty, but it is not enough

Is there a way to search longer for paths at the cost of longer calculation times?

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by strubium** [comment]
I think renderCachedChunks could help with pathing, could let baritone "see" more possible paths.

At least i think that's how it works

**Comment by ZacSharp** [comment]
> I think renderCachedChunks could help with pathing, could let baritone "see" more possible paths.

`renderCachedChunks` is purely visual and allows you to see cached chunks. Baritone can always read any cached cached chunk and unless you enabled `pathThroughCachedOnly` (don't do that) it can also read any chunk in your render distance.

You can
1. disable `allowBreak`
2. crank up `blockBreakAdditionalPenalty` to some ridiculous value like 10000 ticks (about 8 minutes)
3. Not have a tool on you

Calculating worse paths is actually faster in many cases. Just increase `costHeuristic` by a bit to try it out. Don't overdo it thoug since iirc increasing `costHeuristic` to n times the default value allows for paths roughly n times longer than the shortest path.
