### ISSUE TITLE
How do I tell baritone to only #mine for a specific block in a specific block state

### ISSUE THREAD

**Issue by Hi1307** [cabaletta/baritone#3920]
## What do you need help with?
With as much detail as possible, describe your question and what you may need help with.

I would only like Baritone to mine fully grown cocoa beans. How do I do that (1.12.2 Forge)? Thank you!

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
For minecraft 1.12.2 you can specify a meta value (`#mine <namespace>:<name>:<meta>`).
It normalizes some values so you can't specify the direction, but the different growth stages are kept distinct so you can mine fully grown cocoa facing in any direction using `#mine minecraft:cocoa:10`.

**Comment by Hi1307** [comment]
Thank you for the help! Why is 10 the correct value for this operation, when the age of the bean is actually 2?

**Comment by ZacSharp** [comment]
Every state has it's own meta value so 0-3 is age 1 in four directions, 4-7 is age 2 in four directions and 8-11 is the four states for age 3. Without Baritone ignoring some properties you would need `#mine cocoa:8 cocoa:9 cocoa:10 cocoa:11`, but since Baritone treats all cocoa blocks as if they were facing north you only have to specify the one for north facing age 3 cocoa, which is `cocoa:10` (in fact, the other directions won't work at all).
To find out which meta value is which state you can simply try them all. Meta values can only be 0-15 (yes that does mean in mc 1.12.2 and earlier no block can have more than 16 distinct states).
