### ISSUE TITLE
Is there a better way of managing block lists?

### ISSUE THREAD

**Issue by LysiBee** [cabaletta/baritone#3933]
## I noticed that the block list cannot be supplemented with other blocks 
(if you have `cobblestone, dirt` and want to add `grass`, you need to write `cobblestone, dirt, grass`. Not much of a problem with small lists, but becomes a problem when you need to write 15+ blocks)
you always need to write a new block list. Maybe there is another way to quickly create a block list? 

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
1. What kind of list are you talking about? Lists in settings can't contains spaces and "lists" in commands like `#mine` can't be separated by commas (because it's a bunch of arguments and not a list)
2. Assuming you want to add an entry to a `List<Block>` setting: You can use tab completion to fill in the previous value and then edit it. Alternatively you can close the game, edit `<minecraft folder>/baritone/settings.txt` and start mc again.

**Comment by LysiBee** [comment]
> 1. What kind of list are you talking about? Lists in settings can't contains spaces and "lists" in commands like `#mine` can't be separated by commas (because it's a bunch of arguments and not a list)
> 2. Assuming you want to add an entry to a `List<Block>` setting: You can use tab completion to fill in the previous value and then edit it. Alternatively you can close the game, edit `<minecraft folder>/baritone/settings.txt` and start mc again.

I was talking about list's of blocks, that baritone can throw, avoid breaking etc, thanks for your response
