### ISSUE TITLE
mining reset

### ISSUE THREAD

**Issue by Nakmana** [cabaletta/baritone#3937]
Is there a way to make it detect that there're new blocks it needs to mine without #sel ca'ing every time?

**Comment by rycbar0** [comment]
Yes and no. How about rephrasing your question? Once you've done that, I'll rephrase my answer.

**Comment by Nakmana** [comment]
Right now I have baritone automining at a private mine on a prison server.

It mines layer by layer until the mine resets using #sel 1 and #sel 2, but each time the mine resets Baritone mines straight down to where it was and just stands there.

**Comment by rycbar0** [comment]
short answer no. to understand why we need to take a quick excursion behind the sceens on how the clear area works.
cleararea creates a "air schematic" which means baritone trys to "build" a air cube. as long as baritone is working on such a cube it will scan for incorrect blocks and will detect new blocks. once it is finished with that schematic it no longer cares for that part of the world. build in layers takes a big schematic and cuts it into multiply small schematics. this means while baritone is working on a layer it will detect changes on that layer, but once the layer is finished and it continous to the next i no longer cares about it.

**Comment by ZacSharp** [comment]
The overall answer is correct ("No, you can't have it restart from layer 1 without running the command again"), but the reasoning is slightly off:
`buildInLayers` does not split the schematic into multiple schematics (`BuilderProcess` doesn't even have a feature that would allow building multiple schematics one after the other), instead it creates a schematic which at first includes only the first layer and with each completed layer it **adds** the next layer.

This does mean however, that the behavior you described should not happen. The expected behavior is that once the mine resets Baritone goes on clearing it, but not layer by layer because the schematics goes from layer 1 down to the lowest layer it has reached so far.

If you make your selection a single layer and repeat downwards with `buildRepead 0,-1,0` you get exactly the behavior @rycbar0 described (stops caring about a layer once it's done).
