### ISSUE TITLE
This mod doesn't work with Immersive Portals (1.19.4)

### ISSUE THREAD

**Issue by AdolfRoxler** [cabaletta/baritone#3939]
## Some information
Operating system: Linux
Java version: 17
Minecraft version: 1.19.4
Baritone version: I don't know. My best guess is latest - https://github.com/MeteorDevelopment/meteor-client/issues/3649
Other mods (if used): Immersive Portals

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Install Immersive Portals and you're set for uselessness

## Modified settings
None.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

## Reference
https://github.com/cabaletta/baritone/issues/2369

**Comment by rycbar0** [comment]
https://github.com/cabaletta/baritone/issues/2369#issuecomment-773721716

**Comment by AdolfRoxler** [comment]
I already mentioned the issue

**Comment by rycbar0** [comment]
yes and the issue contains the solution: uninstall immersive portals

**Comment by AdolfRoxler** [comment]
Burning down a house because it has cockroaches isn't a good idea, now is it?

**Comment by wagyourtail** [comment]
Dear @AdolfRoxler ,

Thank you for bringing your concerns to our attention. We understand that you are frustrated with the current situation, but it's important to note that creating duplicate issues does not help us resolve the problem any faster. In fact, it can lead to confusion and inefficiency in our efforts to provide support.

The previous issue you linked is still open, and we are aware of it. However, the suggested solution of uninstalling "Immersive Portals" has been identified as a potential fix for the problem. We understand that this may not be an ideal solution for you, but at the moment, it is the best workaround available.

Please keep in mind that we strive to support a wide range of mods and configurations, but it's not always practical to address every individual case due to technical limitations and compatibility issues. We appreciate your understanding in this matter.

Continuing to create duplicate issues and expressing your frustration in an unconstructive manner may result in limitations on your ability to open or participate in discussions on issues. We encourage you to maintain a respectful and collaborative approach to help us address the problem effectively.

Thank you for your cooperation.

Best regards,
Wagyourtail
