### ISSUE TITLE
How to make baritone find a more optimal and faster path,search in a much bigger area?

### ISSUE THREAD

**Issue by GiorgosSid** [cabaletta/baritone#3958]
## 
Sometimes baritone just dont find the best path(it finds a path that is the closest that way but takes more time than a path that is longer),also the goto command should be able to get configured so you should select the amount of block(radius) to search.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
Search distance is only limited by whether Baritone knows the terrain so as long as the necessary areas are cached it can search far outside your render distance.
The reason why it stops early is more likely a timeout. If you start pathing it works as follows
1. If it finds a complete path to your goal it uses that.
2. After `primaryTimeoutMS` if there is a long enough partial path, it uses that instead of waiting for a complete one any longer.
2. After `failureTimeoutMS` if there is still not even a long enough partial path, it fails.

If it is already walking and planning ahead it uses `planAheadPrimaryTimeoutMS` and `planAheadFailureTimeoutMS` instead.

You are probably running into 2. either for the initial segment or for a following segment so I'd suggest increasing all four timeouts.

**Comment by pennilessSplatter** [comment]
> Search distance is only limited by whether Baritone knows the terrain so as long as the necessary areas are cached it can search far outside your render distance. The reason why it stops early is more likely a timeout. If you start pathing it works as follows
> 
> 1. If it finds a complete path to your goal it uses that.
> 2. After `primaryTimeoutMS` if there is a long enough partial path, it uses that instead of waiting for a complete one any longer.
> 3. After `failureTimeoutMS` if there is still not even a long enough partial path, it fails.
> 
> If it is already walking and planning ahead it uses `planAheadPrimaryTimeoutMS` and `planAheadFailureTimeoutMS` instead.
> 
> You are probably running into 2. either for the initial segment or for a following segment so I'd suggest increasing all four timeouts.

This is extremely useful information. Noting to self.
