### ISSUE TITLE
I could help make a simple official website if you don't have one already

### ISSUE THREAD

**Issue by Flappy25** [cabaletta/baritone#4027]
## Describe your suggestion
An official website would help popularize the baritone project and make it more accessible to more people 

## Settings
I won't be able to host the server but I can design it

## Context
More people can use baritone, more accessible to many people. 

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by rycbar0** [comment]
for a website there are 3 things needed
1. a domain name so your site can be found
2. a hoste server
3. a html so the server can respond to a request with a website 

registrating a domain name to my knowlage is around 15$ / year but can be more for special names
hosteing a server costs monthly when you rent it or if you home hosting you have to pay for electicity, internet connection etc

also how would a official baritone website help popularity? i think making a official appearance on already established minecraft mod sites like courseforge or modrinth would be way more effective than hosting our own website.

one thing i think could be done, because people are stupid and lazy is to somehow make the "download" button of the readme.md bigger and visible without the need to scroll 1/2 a page down. but that is spoon feeding people who would rather bombard the discord with "where can i download baritone?" pinging everyone and wait 6h for someone to respond than scroll down a web page

**Comment by Flappy25** [comment]
> for a website there are 3 things needed
> 1. a domain name so your site can be found
> 2. a hoste server
> 3. a html so the server can respond to a request with a website 
> 
> registrating a domain name to my knowlage is around 15$ / year but can be more for special names
> hosteing a server costs monthly when you rent it or if you home hosting you have to pay for electicity, internet connection etc
> 
> also how would a official baritone website help popularity? i think making a official appearance on already established minecraft mod sites like courseforge or modrinth would be way more effective than hosting our own website.
> 
> one thing i think could be done, because people are stupid and lazy is to somehow make the "download" button of the readme.md bigger and visible without the need to scroll 1/2 a page down. but that is spoon feeding people who would rather bombard the discord with "where can i download baritone?" pinging everyone and wait 6h for someone to respond than scroll down a web page

Ok I guess you are right, I just thought that it could help defeat baritoneminecraft.com

**Comment by Flappy25** [comment]
> for a website there are 3 things needed
> 1. a domain name so your site can be found
> 2. a hoste server
> 3. a html so the server can respond to a request with a website 
> 
> registrating a domain name to my knowlage is around 15$ / year but can be more for special names
> hosteing a server costs monthly when you rent it or if you home hosting you have to pay for electicity, internet connection etc
> 
> also how would a official baritone website help popularity? i think making a official appearance on already established minecraft mod sites like courseforge or modrinth would be way more effective than hosting our own website.
> 
> one thing i think could be done, because people are stupid and lazy is to somehow make the "download" button of the readme.md bigger and visible without the need to scroll 1/2 a page down. but that is spoon feeding people who would rather bombard the discord with "where can i download baritone?" pinging everyone and wait 6h for someone to respond than scroll down a web page

I guess your right
