### ISSUE TITLE
Can't jump to slabs

### ISSUE THREAD

**Issue by TiagoferMC** [cabaletta/baritone#405]
If you have a block with a slab on it, baritone will have trouble pathfinding to it.

Say, in the following image, that I want to jump to the slab on top of the middle block. Baritone will be unable to pathfind either through the left slab or the right block. (Although before I broke the terrain around it, it did pathfind by jumping from a block nearby).

<img width="960" alt="Parkour" src="https://user-images.githubusercontent.com/4838199/56758825-70aed100-678f-11e9-9fc1-ba2d33cb3d0b.png">

For a more realistic scenario look no further than the parkour challenge in the hub of Geographica (geographica.xyz) (1.12.2). Again, Baritone is unable to pathfind to any block in the course. (Except, of course, the starting slab.)

<img width="960" alt="Parkour Geographica" src="https://user-images.githubusercontent.com/4838199/56761425-334d4200-6795-11e9-8e6f-b806acd74e4d.png">

Tested on both Impact 4.6-beta (1.12.2) which runs Baritone API version 1.2, and Impact 4.6 (1.13.2) which runs version 1.3.

I couldn't find any recent issue about this. If it has already been fixed in the current version of the API and Impact just hasn't updated then I'm sorry for the time wasted.

**Comment by leijurv** [comment]
Sorry, Baritone is not a parkour bot it's a pathfinding bot. Will not be adding movements for every possible parkour jump. Jumping to or from bottom slabs or stairs is disallowed anyway because it's far too inconsistent. It can make straight jumps across 1, 2, or 3 block gaps, but only for the purpose of getting from point A to point B, not for trivial parkour challenges.
