### ISSUE TITLE
which one

### ISSUE THREAD

**Issue by kizuru22** [cabaletta/baritone#4088]
when i go to the download page of baritone should i then pick both: baritone api, baritone standalone and baritone unoptimized. its for fabric btw

**Comment by ZacSharp** [comment]
You only need one jar, there's a list [here](https://github.com/cabaletta/baritone/blob/master/SETUP.md#artifacts).
The reason that there is multiple jars per platform is that standalone can provide better performance than api but cannot be used by other mods and unoptimized is a bit slower than api but very useful for debugging.
If you need a log file or crash report to report a bug, that's when you should use an unoptimized jar, otherwise use api or standalone depending on your other mods.
