### ISSUE TITLE
Baritone for 1.20.2 not working for Fabric or Forge

### ISSUE THREAD

**Issue by mrow921** [cabaletta/baritone#4155]
No other mods present except Fabric API. All for version 1.20.2.

When I install Baritone API / Standalone API, it's as if it isn't recognised. I can't use any # commands as it seems the mod isn't installed, despite being in the relevant mods folder. Any fixes?

**Comment by Nuclearpotato69** [comment]
mabye cause theres not a official release yet

**Comment by ZacSharp** [comment]
For minor Minecraft updates there's a realistic chance that Baritone keeps working (it always did so far, except for 1.18.1 -> 1.18.2).
Lacking further information my guess is that you are using the wrong file. Make sure you are using a jar with "-fabric-" somewhere in it's name.

**Comment by wagyourtail** [comment]
> For minor Minecraft updates there's a realistic chance that Baritone keeps working (it always did so far, except for 1.18.1 -> 1.18.2).

this is no longer the case since mojang announced https://help.minecraft.net/hc/en-us/articles/9971900758413-Major-Minor-Versions-in-Minecraft-Java-Edition

**Comment by ZacSharp** [comment]
Uh, more incompatibilities per year, very nice.
But surely Fabric wouldn't just silently ignore a mod because it's for the wrong minor version, right?

@mrow921 did you install Baritone for 1.20.1 (release v1.10.1) or for 1.20.2 (CI built or self built)?
EDIT: It's probably best if you tell us which specific file you used and post a log in case it contains interesting output (fabrci version, whether Baritone is in the mods list and maybe some error / info messages)

**Comment by cohejh** [comment]
This problem affects the release 1.10.1 and the elytra beta, and it's currently not compilable for 1.20.2, if you change the code to allow it to run on 1.20.2, it will not compile correctly and throw errors.
 
<img src="https://i.imgur.com/yCfPB0S.png">
<img src="https://i.imgur.com/xu7iZUW.png">

**Comment by wagyourtail** [comment]
where do we say release 1.10.1 supports 1.20.2? use the CI build, and make sure to pick the right file. (tho it needs a new build that merges #4145 )
