### ISSUE TITLE
How do I build baritone 1.20.2 properly

### ISSUE THREAD

**Issue by kubaaa203** [cabaletta/baritone#4181]
## What do you need help with?
With as much detail as possible, describe your question and what you may need help with.
I built baritone with the gradlew.bat file but there is still no "dist" folder in which are supposed to be artifacts...

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
Assuming you used https://github.com/cabaletta/baritone/blob/1.19.4/SETUP.md#build-it-yourself as a guide you probably just ran `gradlew`, which is not enough. I have no idea why the instructions only mention the command without arguments. Since you want to build for 1.20.2 simply running `gradlew build` should be enough to build everything, on older versions you might need an extra step and/or extra arguments.

**Comment by kubaaa203** [comment]
Where do I find this `gradlew build`?

**Comment by ZacSharp** [comment]
Should be the same file? If that doesn't work you'll need someone else to help you as I have never used a command line on windows.
