### ISSUE TITLE
Security Exception error

### ISSUE THREAD

**Issue by theneket** [cabaletta/baritone#4200]
## What do you need help with?
I'm getting a SecurityException error when trying to run the example API code in my custom client. I'm using Minecraft Coder Pack 9.40 (1.12.2). The error is `java.lang.SecurityException: class "ain"'s signer information does not match signer information of other classes in the same package`
Here is the code below (taken from example):
```java
BaritoneAPI.getSettings().allowSprint.value = true;
BaritoneAPI.getSettings().primaryTimeoutMS.value = 2000L;

BaritoneAPI.getProvider().getPrimaryBaritone().getCustomGoalProcess().setGoalAndPath(new GoalXZ(10000, 20000));
```

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
This sounds like a problem with your setup. Baritone can be tricky to get working in certain environments, but since the exception you got is about a Minecraft class and not about anything from Baritone I'd guess Baritone has nothing to do with the exception.
If you think Baritone is the problem, please make sure the Baritone jar you are using actually uses the mappings you need.

**Comment by wagyourtail** [comment]
Delete meta-inf
