### ISSUE TITLE
When I do #mine shulker_box it mines any shulker boxes close to me and then starts digging into the ground

### ISSUE THREAD

**Issue by Platinum2500** [cabaletta/baritone#4209]
Operating system: Windows 10
Java version: Version 8 Update 301
Minecraft version: 1.19.4
Baritone version: fabric-1.9.3
Other mods (if used): 

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ ] I have included logs, exceptions and / or steps to reproduce the issue.
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by Booogyboooo** [comment]
Is there any shulker boxes under the ground?

**Comment by ZacSharp** [comment]
Actually, this doesn't look like a genuine bug. Just some unexpected behavior.
Once there are no known target blocks left it starts searching for more (at least if `legitMine` or `exploreForBlocks` is enabled) and since it is made to search for ores it will by default prioritize lower y values (configurable using `legitMineYLevel`, default is -59).
