### ISSUE TITLE
How Can I set buildInLayers and buildignoreexisting in forge

### ISSUE THREAD

**Issue by uwuv3** [cabaletta/baritone#4220]
## What do you need help with?

I want to create any schema but sometimes ai loops and I want to turn on buildInLayers and buildignoreexisting settings to stop it

- #buildInLayers and #buildignoreexisting commands give "Invalid command" Error
 
![image](https://github.com/cabaletta/baritone/assets/100004271/3b9f92f7-1fb3-4c2b-ac22-8bb40a2acd3c)

- <strong>#set buildInLayers true</strong> and <strong>#set buildignoreexisting true</strong> commands give "Expected a valid value"

![image](https://github.com/cabaletta/baritone/assets/100004271/90968b82-3f40-4c4c-bf16-44bc8e7b0606)

## Mod list
- [x] WorldEdit & WorldEdit CIU
- [x] Baritone API
- [x] Optimization Mods (ex. Lithium, Sodium, MemoryLeakFix, ModernFix)
- [x] Better F3

## Checked Issues
- #1768 
- #1353 
- #2166 

## Final checklist
- [x] Minecraft Version: 1.20.1 (Fabric 0.15.2)
- [x] Baritone Version: Null version (dev version)
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
You are probably using https://github.com/cabaletta/baritone/releases/tag/v1.10.1 but downloaded it via a tlauncher mirrored version of an unofficial CurseForge project which just reuploaded the official release file. Maybe reconsider your download sources and stop pirating Minecraft.

Things should work the way you tried using them in the screenshots so maybe try removing mods or use a proper launcher which doesn't do weird thing to the game in order to function.
