### ISSUE TITLE
how do i make baritone ignore blocks that are in place of a block in the schematic, but not the correct block

### ISSUE THREAD

**Issue by DenouementEfflorescence** [cabaletta/baritone#4231]
## What do you need help with?
I am trying to make baritone build a schematic for me (cuz im lazy) but since i am building with grass for this, or rather baritone, the grass keeps turning into dirt. so baritone keepss mining the dirt, making minimal progress. how do i make baritone just say "that block isnt in the schematic and theres supposed to be grass here and not dirt? well i dont care" and just keeps building. and for the sake of me not having to check the second box, here. OwO

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
There are some options, depending how much Baritone should not care about the block:
* If it should completely ignore the fact that there's grass in your schematic use `#set buildSkipBlocks grass` (no guarantees on the block id). It effectively "punches holes" into your schematic.
* If it should just allow dirt to be in places where the schematic demands grass use `#set buildValidSubstitutes grass->dirt`. Baritone will place grass but also won't care if there is already dirt or grass turns into dirt
* If it should place dirt or grass where the schematic demands grass use `#set buildSubstitutes grass->grass,dirt` or `#set buildSubstitutes grass->dirt,grass`. The order determines which one it will prefer.
* If it should only accept dirt instead of grass, use `#set buildSubstitutes grass->dirt`



The final checklist is there to help you write a well formed question and being unable to tick one of the boxes probably means your question is invalid and will not be answered :smirk:

**Comment by DenouementEfflorescence** [comment]
thanks! but i have used OwO's

**Comment by DenouementEfflorescence** [comment]
btw is there also any way to make it consider effects like jump boost?

**Comment by ZacSharp** [comment]
Haste is automatically accounted for and iirc Baritone can walk on lava if you have a jesus hack but it can't swim in lava (whyever). I think speed is not considered while pathing but normal speed levels should at least not trip it up, and the same goes for low levels of jump boost as long as you don't make it walk below a lava ceiling or similar.

**Comment by DenouementEfflorescence** [comment]
hm. doesnt  really work... i used #set buildValidSubstitutes grass->dirt but it still mines dirt that is inplace of grass...

**Comment by ZacSharp** [comment]
As I said, the block id might be wrong. Grass blocks and tall grass switched ids around some years ago and I never managed to remember which one is the new naming.
According to https://minecraft.fandom.com/wiki/Grass_Block#ID the current id is `minecraft:grass_block` so the command is `#set buildValidSubstitutes grass_block->dirt` (if you are on 1.13+)

**Comment by Rajeshvat123** [comment]
Ok
