### ISSUE TITLE
unable to fill in water 

### ISSUE THREAD

**Issue by johnmarshVII** [cabaletta/baritone#4235]
I am trying to fill in a large area of water using baritone but it seems to get confused and just sinks me to the bottom. Is there anything I can do to make it fill in the water?

**Comment by johnmarshVII** [comment]
ive tried using sel cleararea and sel fill , but neither work

**Comment by ZacSharp** [comment]
`#sel cleararea` is effectively the same as `#sel fill air` so that's to be expected.
The problem with what you want to do is that Baritone can only swim on the surface so there is no way for it to reach the positions where it has to place the block. The reason it sinks down is that it defaults to not doing anything at all, which is a bit questionable when in water.
If you want to get rid of the water you could try replacing the top layer with solid blocks, then removing those and replacing the next layer until all water is removed.
