### ISSUE TITLE
Baritone not mining grass blocks without scaffolding if there are no blocks underneath them

### ISSUE THREAD

**Issue by DenouementEfflorescence** [cabaletta/baritone#4236]
## What do you need help with?
Baritone not mining grass blocks without scaffolding if there are no blocks underneath them, instead scaffolding underneath the blocks. i dont want that. i want it to stay ontop of the selection and just.. stand on the grass blocks while mining them.. how hard could that be?    im working on a project right now and it basically makes it really annoying as i dont have enough blocks to just let baritone scaffold around like that. how do i fix it?

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by wagyourtail** [comment]
`#allowDownward` iirc

**Comment by ZacSharp** [comment]
That alone won't help since `allowDownward` only enabled/disables `MovementDownward` and because `BuilderProcess` by default does not break from above Baritone will use weird combinations of `MovementDescent` and `MovementFall` to go down anyway.

To allow `BuilderProcess` to break blocks from above enable `breakFromAbove` and ~`allowBreakFromAbove`~`goalBreakFromAbove`. It should now prefer staying above the surface as long as it is there. If it still scaffolds around too much you can try disabling `allowPlace`. Depending on your surroundings disabling `allowDownward` might also make it less likely to go below the surface.

**Comment by DenouementEfflorescence** [comment]
yea. but it still does nothing. it just stands there trying to find  a path insted of breaking the grass blocks from above

**Comment by ZacSharp** [comment]
You have `breakFromAbove` and `goalBreakFromAbove` enabled? (I used the wrong name in my previous comment, sorry).

**Comment by DenouementEfflorescence** [comment]
let me check
