### ISSUE TITLE
Baritone Incompatiblity with JustEnoughIds

### ISSUE THREAD

**Issue by zXord** [cabaletta/baritone#4237]
## Some information
Operating system: Win 11
Java version: 1.8.0_51, Oracle Corporation
Minecraft version: 1.12.2
Baritone version: 1.2.19
Forge version: 14.23.5.2860
Other mods (if used): 
JustEnoughIds - version 1.0.3-55
thebetweenlands - version 3.5.10
----
I tested this on SevTech ages modpack but tracked it to the mod: JustEnoughIds.

## Exception, error or logs
[latest.log](https://github.com/cabaletta/baritone/files/13855195/latest.log)

## How to reproduce
-run Minecraft, and it crashes before loading the mods (doesn't reach 2/7 in forge).

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
Looks like this is caused by [this mixin](https://github.com/DimensionalDevelopment/JustEnoughIDs/blob/4d7f1fc4ff3afd965e698f98f998c1d5072518db/src/main/java/org/dimdev/jeid/mixin/init/JEIDMixinLoader.java#L21) in JEID so I wonder whether this happens without Baritone.

Might be a duplicate of https://github.com/DimensionalDevelopment/JustEnoughIDs/issues/183 or a similar issue on the JEID repo and if so should be handled there.

**Comment by zXord** [comment]
i tried the latest version from that github with baritone, but still it doesn't load it.
without baritone the game works fine.

**Comment by wagyourtail** [comment]
did you also add MixinBootstrap? (<https://modrinth.com/mod/mixinbootstrap>)

**Comment by zXord** [comment]
> did you also add MixinBootstrap? (https://modrinth.com/mod/mixinbootstrap)

ooh I didn't think it was a mod!

i added it now with version 1.0.4 beta jeids
and it works.

Thanks!
