### ISSUE TITLE
Baritone ignores ores while mining

### ISSUE THREAD

**Issue by theagrik** [cabaletta/baritone#4241]
## Some information
Operating system: Windows 10 (22H2) x64
Java version: openjdk 21.0.1 2023-10-17 LTS
Minecraft version: 1.20.4
Baritone version: fabric-1.10.2
Other mods (if used): Xaero's Minimap + Worldmap; Fabric API

## Exception, error or logs
[bugrep.log](https://github.com/cabaletta/baritone/files/13885532/bugrep.log)

[Showcase (on Google Drive)](https://drive.google.com/file/d/11CxIQ2bW6tqAFk09UMo8qxhJBTE0_k6O/view?usp=sharing)

## How to reproduce
Just run #mine with some ore. Worked to me with iron and coal.

## Modified settings
None

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by m0reD3l1r1um** [comment]
this problem is even worse with ores not generated as a vein but simply placed on the surface of a wall

https://drive.google.com/file/d/1gCzCUZBX2VPTrfrY5SQNit7_5Bpaustc/view?usp=sharing

it has something to do with #allowBreak false. it can't aim at blocks not on sight hight (sry for my english...)

https://drive.google.com/file/d/1mQdQn5tLye2A7HFVZg94UihsHynXIB51/view

**Comment by ZacSharp** [comment]
@m0reD3l1r1um yes, Baritone mines ores only if it can walk into their position (and in some cases straight up) so mining that copper without being able to break the stone is expected to not work (also you must have put copper on `allowBreakAnyway` or it would have refused mining in the first place). Your problem is different from what @theagrik showed in their video and hence unrelated to this issue.

@theagrik this might the same as #4216 so if you can, please try increasing the `ORE_LOCATIONS_COUNT` in `MineProcess.java` and test whether that helps?
