### ISSUE TITLE
Baritone wont move when #mine is executed

### ISSUE THREAD

**Issue by 1Arthur120** [cabaletta/baritone#4254]
## Some information
Operating system: Windows 10
Java version: 8
Minecraft version: 1.20.2
Baritone version: 1.2.19

## How To Reproduce
you basically execute #mine, it simply wont move, it finds the path, but will never move, theres no other information i can provide other than that, i just got baritone and thats it, it wont move, btw this baritone version has support for 1.20.2, according to a user post.

## Modified settings
None

## Final checklist
- [x] I know how to properly use check boxes 
- [X] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [X] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
Baritone 1.2.19 is for Minecraft 1.12.2 and running it on Minecraft 1.20.2 would involve large amounts of black magic so you probably got some numbers wrong there. And no, there is no released version with support for 1.20.2.

Regarding further information you could provide: The issue template has a section asking for a log file. You could provide the file instead of deleting the section.

**Comment by ZacSharp** [comment]
Just remembered CI version numbering was a *bit* weird in that it would use the closest possible release version, even if that meant following a merged-in branch all the way down to master (1.12.2). If your version is v1.2.9-hugenumber (hugenumber being somewhere in the hundreds) then that's what happened.

**Comment by 1Arthur120** [comment]
Is there any baritone version for 1.20.2?

**Comment by ZacSharp** [comment]
Only CI builds. If you tell me the precise version (including the "-ghexnumber" part) I can check whether you got the right one.

**Comment by 1Arthur120** [comment]
Please tell me a version i can use for 1.20.2

**Comment by ZacSharp** [comment]
All successful CI builds on the 1.20.2 branch from newest to oldest:

Version number | Guessed version | Artifacts | Date
-|-|-|-
v1.2.19-599-ga223585d | v1.2.19-599-ga223585da | expired | Jan 6, 2023
idk | v1.2.19-597-ga945cfaa3 | expired | Oct 31, 2023
idk | v1.2.19-591-g9bf890a7b | expired | Sep 28, 2023
idk | v1.2.19-588-ge1e620a0d | expired | Sep 28, 2023
idk | v1.2.19-588-gf5d15927d | expired | Sep 25, 2023

Apparently all places where the version number is used vanish once the artifact retention period is over so I locally generated the version numbers from the commit hash and as you can see in the first row that's not 100% precise. If one version string looks like another one but shorter it's probably the same version.

EDIT: Since all workflow artifact are expired, [here](https://github.com/cabaletta/baritone/files/14320055/Artifacts.zip) are the results of the last run as an attachment.

**Comment by 1Arthur120** [comment]
Ty
