### ISSUE TITLE
Enable execute to be able to make carpet bots mine for you.

### ISSUE THREAD

**Issue by T4rt4rus** [cabaletta/baritone#4268]

**Comment by The-Rokayan** [comment]
Well... you're asking for an addition that would need a total rewrite of how the incoming data is analyzed and how the input is sent,

First, it would need to be a server side mod, since carpet is also server side,

Though it would be nice in a way, a legal bot that plays with you can be a minigame by itself, It would make for a cool game and a revolutionary feature in minecraft, integration of a true AI. A super Mob.

You can use the scripting provided by carpet and post it as scarpet :3

I think it's maybe possible to port baritone into carpet, abstraction exist afterall, 

Well... or you can simply use Automatone... (they have ported it server side)

**Comment by ZacSharp** [comment]
As @The-Rokayan said, Baritone is a client side mod intended to control real Minecraft clients while carpet is server side (with optional client side stuff) and the whole point of Carpet bots is not needing a real client.
The existence of Automatone proves that the necessary refactoring would be possible, but without having had a look at their changes so far I can't tell whether a corresponding pr would be accepted. If any of the additional abstractions have too much of a performance penalty that's a non starter. (Also if anyone wants to put effort into such a pr, ask leijurv first)
