### ISSUE TITLE
baritone not building

### ISSUE THREAD

**Issue by Malakae** [cabaletta/baritone#4276]
## What do you need help with?
I can't get baritone to build my schematic. It just immediately says "Done building" in chat when I try and use #litematica 
## Final checklist
[latest.log](https://github.com/cabaletta/baritone/files/14317567/latest.log)
![settings](https://github.com/cabaletta/baritone/assets/46078509/d9f98e6a-41fa-44c4-9ad5-2c1eb45a3cf9)

- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
Here's a few guesses
* What Litematica version are you using? If it's too new it might be incompatible and I don't know how Baritone would behave in that case (probably a crash but who knows)
* Did you try removing sodium chunk management? Once again I'd expect different behavior but don't know for sure.
* Do you have more schematic placements?

In general you should try to rule out / confirm incompatibilities by removing as many mods as possible and maybe try building the same schematic from a file instead of using `#litematica`
