### ISSUE TITLE
why isn't 1.20.2 supported/ when will it be?

### ISSUE THREAD

**Issue by Maracujacraft** [cabaletta/baritone#4298]
So basically my problem is, that currently there is no version, that supports 1.20.2

**Comment by ZacSharp** [comment]
That's because the target version is always the latest minor version of each supported major version and 1.20.3 was released before any Baritone release for 1.20.2 was made. The latest Baritone release supports 1.20.3 as well because 1.20.3 happens to be basically identical to 1.20.4.

If you need a build for 1.20.2 look at the bottom of this comment https://github.com/cabaletta/baritone/issues/4254#issuecomment-1922291720.

**Comment by Booogyboooo** [comment]
use viafabricplus or viaforge
