### ISSUE TITLE
java.lang.NoClassDefFoundError: baritone/api/pathing/goals/Goal

### ISSUE THREAD

**Issue by maint623** [cabaletta/baritone#4381]
## What do you need help with?
java.lang.NoClassDefFoundError: baritone/api/pathing/goals/Goal
I'm trying to use baritone in the mod but I'm getting a NoClassDefFoundError
I used shadow jar, minecraft version is 1.19.4, baritone version is 1.9.3
I also imported baritone-api-forge-1.9.3.jar from the libs file and added dependencies, but an error appears.
![image](https://github.com/cabaletta/baritone/assets/98867089/3ec9665b-5a85-4465-ba79-6530f4b2f57d)
![image](https://github.com/cabaletta/baritone/assets/98867089/68b2b5b6-c705-492f-82a4-8a2e417e7f23)

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
A bunch of guesses / questions:
How are you running the game? Why are you including Baritone twice (though that shouldn't cause NoClassDefFoundError)? Which maven repository does the maven dependency come from?
`baritone-api-forge-1.9.3` should be the correct jar, but the maven dependency is probably not what you want.
Did you try adding Baritone separately instead of using shadowing? Are you sure shadowJar picked up the dependency?
