### ISSUE TITLE
Make allowBreakAnyways an array of blocks

### ISSUE THREAD

**Issue by brentspine** [cabaletta/baritone#4386]
## Describe your suggestion
The allowBreakAnyways option allows the client to break a certain block, even if allowBreak is set to false. My suggestion is, that it allows multiple blocks in this option, instead of only one singular. 

## Example
I want the bot to mine multiple types of ores in a cave, but don't want to allow breaking stone. For this I would set allowBreak to false and set allowBreakAnyways to diamond ore. Now it will only break diamond ores and no stone. But what if there is also deep slate diamond ore. We would need to decide which one we want. This is why I suggest we allow multiple blocks as the value of allowBreakAnyways 

## Final checklist
- [x] I don't know how to properly use check boxes 
- [] I have not used any OwO's or UwU's in this issue.
- [x] I've searched for similar issues
- [x] Does anybody read these anymore?
- [x] \OwO/

**Comment by ZacSharp** [comment]
You can already separate multiple blocks by commas (not spaces) to do this.
In your case that would be `#set allowBreakAnyway diamon_ore,deepslate_diamon_ore`, though note that mining doesn't work if it can't walk into the positions where the target block is.

Also yes there are people reading the checklist. Please make sure your issue is well formed by removing the extraneous line(s) so you can check the missing box :smile:
