### ISSUE TITLE
my character does not move

### ISSUE THREAD

**Issue by Tweedyzi** [cabaletta/baritone#4388]
Hello, good evening,

I don't know for what reason but when I make the command (sel fill/set/replace minacraft:example)

the character build 
 just what he can build in the radius where this is possible but doesn't move, it tells me that some material is missing even though it is present in my normal inventory?
 
 

https://github.com/cabaletta/baritone/assets/30966798/72621411-e226-4609-a4a1-6ef46bd06a48

**Comment by ZacSharp** [comment]
That's due to the way Baritone tries to guess what can be placed using the materials in your inventory. It can't properly predict blocks which depend on your rotation when being placed so it thinks it can only place bottom slabs.
(When it is already in a position to place a block it will do the same prediction but with the correct rotations so the prediction works and it can place the block even though it didn't know previously)
There are some fundamental problems with trying to predict the block being placed (placement logic is arbitrary code) so it essentially boils down to "someone would have to hardcode it", which nobody did so far.

**Comment by Tweedyzi** [comment]
so impossible?

**Comment by ZacSharp** [comment]
You might have some luck setting `buildIgnoreProperties` to whatever property name slabs use to indicate whether they are a tob/bottom/double slab. It makes Baritone ignore whether the slabs are top/bottom/double, which might work out in your case because placing slabs against top slabs makes them a top slab.
If that doesn't work, then no, not possible without changing code (afaik).

Now I wonder whether ignoring such properties when checking against `approxPlaceable` (the list of predicted block states) would help or make things worse by actively walking to the wrong side of a directional block.

**Comment by Tweedyzi** [comment]
I can try but I don't know how to place the order
