### ISSUE TITLE
Baritone's automine doesn't pick up the mined ores

### ISSUE THREAD

**Issue by User-developer** [cabaletta/baritone#440]
When baritone pathfinds and mines a block type (etc diamond ore), usually the last few diamonds stack and are not picked up. Then, baritone pathfinds to another location, while it could pick up 1-2 more diamonds. Could a pick up checker be added, so baritone checks if the player has inventory space and has picked up the ore?

**Comment by DanFromDiscord** [comment]
Pretty sure it goes back to pick up the last items the next time it recalculates the path. At least that's what consistently happens to me.

**Comment by leijurv** [comment]
It already does this, make sure minescandroppeditems setting is true (it's true by default).

It sometimes goes to the next ore due to server lag (there's a very small period in time after you finish mining the ore but before the item drops), but it'll always come back for those items eventually, since they're a goal option.
