### ISSUE TITLE
Baritone crashes on #path command with Future client

### ISSUE THREAD

**Issue by naorobot11** [cabaletta/baritone#444]
Sorry for not being detailed enough as I have no idea why this is happening. I don't know what to upload so here's two things. 
It seems that other commands work, but #path does not. On singleplayer, it the "server" shutdowns first. I'm also using forge-standalone version with future client. 
[crash-2019-06-06_11.06.34-client.txt](https://github.com/cabaletta/baritone/files/3268975/crash-2019-06-06_11.06.34-client.txt)
https://paste.ee/p/bcC6v

**Comment by leijurv** [comment]
java.lang.ClassCastException: baritone.gm cannot be cast to net.minecraft.util.MovementInputFromOptions
	at chylex.bettersprinting.client.player.PlayerLogicHandler.updateLiving(PlayerLogicHandler.java:67)
	at chylex.bettersprinting.client.player.LivingUpdate.injectOnLivingUpdate(LivingUpdate.java:90)


(from your crash report ^)

This is due to bettersprinting crashing on expecting the player's movement input object to be standard but it's really baritones replaced one. This looks like a fundamental incompatibility between baritone and bettersprinting, can't really fix. Sorry.

**Comment by leijurv** [comment]
(future itself is totally compatible tho)

**Comment by naorobot11** [comment]
Thanks. Purging better sprinting.
