### ISSUE TITLE
Issue with auto mine

### ISSUE THREAD

**Issue by SuzHiy** [cabaletta/baritone#4446]
If custom drops are added to the original items in the server,For example, added a probability of dropping ic2plug-in/mod minerals in the diamond mine， using #mine will result in an error and cannot be used.

**Comment by ZacSharp** [comment]
It would help if you included a log file (have a look at the bug report template, it seems to be more fitting for your question).
Since it sounds like you are using a modpack on a server, I'll also add that it would be nice of you could test whether this also happens in singleplayer, with as few mods as possible.
