### ISSUE TITLE
baritone failure

### ISSUE THREAD

**Issue by a6d6061ed1** [cabaletta/baritone#446]
[Here's a clip ](https://streamable.com/4yl59)of baritone falling into lava ocean. Notice how my chat was open when this happened - it wasn't possible for me to cause this (I think). Settings were default except of what I [set in impact's GUI](https://i.imgur.com/3hbRGub.png). Im curious what could be the reason for this to happen? TPS was quite good. I suspect that Efficiency V is causing some problems but Im not sure. Or maybe it was because I opened chat?

**Comment by 2b2tQueueProject** [comment]
this is critical

**Comment by usereewrjrjeejr** [comment]
I've had this without chat open

**Comment by usereewrjrjeejr** [comment]
Baritone straight up fell into lava bridging across a lava lake

**Comment by 0-x-2-2** [comment]
is this on forge with impact

**Comment by a6d6061ed1** [comment]
> is this on forge with impact

yes

**Comment by 0-x-2-2** [comment]
this might be one of the issues it also looks like the server did a setback then baritone tried to recalculate while still walking.

**Comment by leijurv** [comment]
Oh sorry forgot to explain, this is a path executor issue. When the server teleports you backwards along the path it can be tricky to figure out exactly what to do, especially if that position is in the middle of a movement (I.e. Your player feet doesn't match any block position in the path, but it is adjacent to or just above in this case one of them) it needs to figure out what movement it should actually be executing and in this case it failed, I think due to cutting that corner while jumping. Will try and fix. These are really hard to reproduce locally tbh, since there's no lag like this in single player.

**Comment by babbaj** [comment]
the server didn't set him the block he mined briefly came back and pushed him away

**Comment by a6d6061ed1** [comment]
> Oh sorry forgot to explain, this is a path executor issue. When the server teleports you backwards along the path it can be tricky to figure out exactly what to do, especially if that position is in the middle of a movement (I.e. Your player feet doesn't match any block position in the path, but it is adjacent to or just above in this case one of them) it needs to figure out what movement it should actually be executing and in this case it failed, I think due to cutting that corner while jumping. Will try and fix. These are really hard to reproduce locally tbh, since there's no lag like this in single player.

Thank you for this comprehensive answer. I have a question somewhat related to this. Do you know of any spigot/craftbukkit plugin or maybe vanilla mechanic that'd let me artificially lower/cap tps and increase player's latency?

**Comment by leijurv** [comment]
> the server didn't set him back the block he mined briefly came back and pushed him away

well yeah technically, but that dosen't change how it needs to be addressed


@a6d6061ed1 turn on anti desync in impact

**Comment by a6d6061ed1** [comment]
> > the server didn't set him back the block he mined briefly came back and pushed him away
> 
> well yeah technically, but that dosen't change how it needs to be addressed
> 
> @a6d6061ed1 turn on anti desync in impact

it was on

**Comment by leijurv** [comment]
<img width="192" alt="Screen Shot 2019-06-22 at 5 40 47 PM" src="https://user-images.githubusercontent.com/3837873/59970191-e5df1e00-9514-11e9-991e-01148ec9bb44.png">
:thinking:

**Comment by a6d6061ed1** [comment]
> <img alt="Screen Shot 2019-06-22 at 5 40 47 PM" width="192" src="https://user-images.githubusercontent.com/3837873/59970191-e5df1e00-9514-11e9-991e-01148ec9bb44.png">
> 
> 🤔

![javaw_1mwMJ8qjEp](https://user-images.githubusercontent.com/20779962/59970201-7e4ec000-9560-11e9-81c1-e03b525dabe7.png)

**Comment by leijurv** [comment]
lowkey don't believe you that vid does NOT look like what its like what anti desync is on

**Comment by a6d6061ed1** [comment]
> lowkey don't believe you that vid does NOT look like what its like what anti desync is on

Sorry but I can't prove that it was on. Original recording was over 30gb (I record all the time and remove those videos if nothing interesting happens) and it's gone now. You have to take my word for it - I have anti desync enabled all the time. I have the same impression as you, maybe it doesn't look like it was on but it's not really my fault. Sometimes I feel like impact's anti desync is missing something because blocks can disappear from my screen and then if server lags, they appear again.

I have a lot of things hidden from HUD module list, in the video you can see that rainbow enchant, crosshair, light and nametags are enabled but not visible in HUD. Also for a brief second you can probably tell that anti overlay is on.

**Comment by leijurv** [comment]
Skeptical But Ok

regardless, baritone should be able to handle this without anti desync, so it dont really matter it was jsut a suggestion

**Comment by leijurv** [comment]
Alright I have a plan for how to deal with this. I misread your video I thought it was two consecutive ascends but really what happened was a traverse than an ascend to the left, it got lagged back to the first block of the traverse but still did the ascend, which jumped from the wrong angle.

So, I think I finally need to switch movement unreachable detection from a blacklist model to a whitelist. 

For example, Ascend will say unreachable if its Y coordinate is less than its starting position, but it won't say unreachable if its X or Z is wrong.

Each movement will provide a list of block positions in which the player is expected to inhabit while carrying out the movement. For example, traverse will have only two (actually, maybe 3 depending on some weird stuff with slabs, TBD). To deal with weird slab / soul sand / ladder scenarios, it might start with just verification that your X and Z are valid, for some movements. Some others like ascend should look at your entire position.

Simultaneously, PathExecutor will be updated to have a more aggressive lagback system. Basically if the current movement reports unreachable it will try going backwards until a previous movement "knows what to do" with the current player feet position. This is so that it doesn't recalculate from scratch for no reason.

**Comment by SylveonBottle** [comment]
> Original recording was over 30gb (I record all the time and remove those videos if nothing interesting happens) and it's gone now.

Shadowplay / windows 10's DVR
![image](https://user-images.githubusercontent.com/17802843/60399584-27cb1e00-9b2c-11e9-9206-652c690d7df3.png)
