### ISSUE TITLE
Add Auto Minecraft

### ISSUE THREAD

**Issue by RavinClaw** [cabaletta/baritone#4461]
## Describe your suggestion
A feature that when run would do basic / advanced tasks in minecraft by actually playing the game byitself.
for example:
- collect wood -> collect stone -> collect iron -> collect diamond -> collect netherite
- randomly select a schematic -> create a virtual list of materials -> collect those materials -> select a random location -> build the schematic
- check hunger -> if low then collect more food -> eat food

## Settings
If applicable, what settings/customizability should be offered to tweak the functionality of your suggestion.

## Context
This feature would improve baritone as it would make it more difficult to detect someone using baritone as actions like those mentioned are typical minecraft actions that someone would preform.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

*I realize this feature might be impossible but I though that if it might be doable it would be pretty cool to see it being added, I also realize that this is really vague*

**Comment by Hackerokuz** [comment]
This is out of scope for baritone.

Making baritone more difficult to detect also wont be done as baritone is made for anarchy servers and not for use where it is not allawed.

People have been asking for this for a while...

Someone did end up making a bot that can do some of the things you are asking for.

Though its main goal is speedrunning the game.

You can find more info here:
https://hackerokuz.github.io/AltoClef-site/

Here is a YouTube link of a speedrun:
https://youtu.be/AQcNnlkcB5Y

**Comment by ZacSharp** [comment]
Actually, since this is so broad it is not completely out of scope.

Properly building schematics is difficult as hell (harder than some basic planning based task selection), but it is a wanted feature. It is agreed that the current builder is crap and we want a new one, but since then I know of only two attempts to fix it and both stalled way before proof of concept stage.

A big-ass hardcoded behavior tree like the one in AltoClef will indeed not happen for Baritone, but what is on the list of "happy if someone does it" features is easier purpose-made automation (e.g. like [this](https://github.com/cabaletta/baritone/pull/3904#issuecomment-1505859304)).

Also note that the [original AltoClef](https://github.com/gaucho-matrero/altoclef) was discontinued and there are multiple active forks.
