### ISSUE TITLE
how to Flying while using Baritone 

### ISSUE THREAD

**Issue by y3621555** [cabaletta/baritone#4492]
How to use Baritone #goto on a survival server when you have flight?
I want to use this to navigate through the nether.

But every time I use #goto it refuses to use my flight ability, and just sends me straight to the ground.

Can I use #goto with flight somehow?

**Comment by ZacSharp** [comment]
No, not without doing code changes.
If you have some programming experience you can try commenting out some floor checks, make it always enable rather than disable flight and make it press space/shift when it is too low/high, similar to the way it's done in water. From my memories that gives working pathfinding and pretty buggy execution. Would not recommend usage near lava or similar obstacles and I never tested it much (because it's obviously unfit for a pr) so might be there's some flaw making it unusable.
