### ISSUE TITLE
Baritone for 1.20.2

### ISSUE THREAD

**Issue by qeqeqeplayer533** [cabaletta/baritone#4495]
## What do you need help with?
I remember using baritone 1.20.2 fabric downloaded from meteor, but I lost the file and now there are only newer versions downloadable, and I tried find it here and have no results, did 1.20.2 existed?

**Comment by ZacSharp** [comment]
There are commits made for 1.20.2 but there is no release for that version. Meteor usually rebase their fork onto the latest Baritone commit fairly quickly, which is why they had a 1.20.2 download. You can also always get CI builds of the latest Baritone commits, but those expire after 90 days so unless meteor also provides old versions of their fork you will have to build Baritone yourself.
Or you could try using one of the 1.20.* releases.
