### ISSUE TITLE
Nothing works on atm9

### ISSUE THREAD

**Issue by Furiosity3** [cabaletta/baritone#4513]
## Some information
Operating system: Win 11
Java version: 17.0.10.0
Minecraft version: 1.20.1
Baritone version: 1.10.2
Other mods (if used): All the Mods 9 (the modpack)

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Put Baritone into ATM9, run the game, try commands

## Modified settings
None

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.
[latest.log](https://github.com/user-attachments/files/17194632/latest.log)

I don't know why the debug.log is so large. It's been uploading for the last 15 minutes so I gave up on it.

**Comment by ZacSharp** [comment]
This is probably caused by an incompatibility with a mod which heavily modifies how minecraft handles world data (e.g. farsight, c2me, immersive portals). I did not try looking through the mod list to search for known incompatibilities.
If you want to find which mod causes this you can try removing half the installed mods (making sure you don't break dependencies). If the problem persists, repeat with the currently installed half, otherwise with the other half, until just Baritone and the minimum required mods for this problem to occur are left.
