### ISSUE TITLE
Any Way To Mine Specific Mob Spawners?

### ISSUE THREAD

**Issue by Jebula999** [cabaletta/baritone#4515]
I am currently playing ATM9.
I would like to run something like /mine minecraft:spawner[silverfish] etc.

I would like to use it to hunt down specific mob spawners.
I see spawners have NBT tags, and that Baritone allows the use of said tags.

But no idea how to see the NBT tag on the spawner or how to differentiate the different spawners.
![image](https://github.com/user-attachments/assets/235019e0-cc5b-49a7-a6f5-a8dd35a32319)

**Comment by ZacSharp** [comment]
This sadly is not possible. What you are specifying on commands like `#mine chest[facing=north]` are block properties and you can see them at the right side of the debug overlay (f3 to toggle) while looking at the block. Contrary to that, the mob spawned by spawners is stored in their tile entity data (NBT data), so not something you can specify in a `#mine` command. Also tile entity data is not reliably available on the client, since the server typically only sends what is needed (e.g. chests will always appear empty because the server never sends their contents), though in this case I think that would not be a problem.
