### ISSUE TITLE
Receiving an BlockOptionalMetaLookup{[BlockOptionalMeta{block=Block{minecraft:dirt}}]}, blacklisting presumably unreachable closest instance... Error upon using #mine command

### ISSUE THREAD

**Issue by StevenWido** [cabaletta/baritone#4516]
## Some information
Operating system: Windows 11
Java version: 11.0.12
Minecraft version: 1.20.1
Baritone version: 1.10.1
Other mods (if used): BetterMinecraft4

## Exception, error or logs
[latest.log](https://github.com/user-attachments/files/17248945/latest.log)
![Screenshot 2024-10-03 150429](https://github.com/user-attachments/assets/68ca9fae-63f6-4ea3-b11b-8014e2660cc2)
## How to reproduce
#mine *any block*

## Modified settings
No modified settings

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x

] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
This is probably caused by a mod changing how Minecraft handles world data (e.g. immersive portals, c2me, farsight are known to do this.)
In case that's not the case, can you please remove any mods not required to make this happen? You can do so by iteratively splitting your modpack in half (and readding dependencies) and testing with which half the problem still occurs (if none, try a different split).

**Comment by StevenWido** [comment]
farsight was the problem. That's crazy knowledge off the top of your head. Thanks so much!
