### ISSUE TITLE
The follow command isn't working

### ISSUE THREAD

**Issue by GoofyRaspberry** [cabaletta/baritone#4568]
## Some information
Operating system: Windows 11 Home
Java version: 8
Minecraft version: 1.15.2
Baritone version: baritone-standalone-forge-1.5.3
Other mods (if used): I added MixinBootstrap-1.0.2 just in case

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue
[2024-11-22-5.log.gz](https://github.com/user-attachments/files/17878441/2024-11-22-5.log.gz)
Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
#follow player [playername]
## Modified settings
To get the modified settings run `#modified` in game
No modified settings
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by GoofyRaspberry** [comment]
I also tried other variations of #follow and they don't work as well. Also https://github.com/cabaletta/baritone/blob/1.15.2/USAGE.md should be updated and add the other variations too

**Comment by ZacSharp** [comment]
Looks like the bug [this](https://github.com/cabaletta/baritone/pull/3024) pr fixed long ago.
However the 1.15.2 branch went out of support even longer ago, so there's no releases with the fix for 1.15.2.
My personal repository probably has a branch for 1.15.2 with the fix, but please note that those branches are nearly untested and not supported or maintained by anyone.
