### ISSUE TITLE
What is cost coefficient??

### ISSUE THREAD

**Issue by XiaoGanCN** [cabaletta/baritone#4573]
## What do you need help with?
I was using baritone-standalone-forge-1.10.1 and baritone-api-forge-1.10.1 in Minecraft 1.20.1, and got this weird issue
Everything just won't work for me
Haven't modify any settings yet (except for chatDebug for log)
<img width="232" alt="截屏2024-11-29 下午4 06 14" src="https://github.com/user-attachments/assets/08a7f29a-2ab4-4ad4-b1a9-a8fd0ca16d8e">

I can't tell "cost coefficient" is a feature or something? searched all over https://baritone.leijurv.com/baritone/api/Settings.html#field.detail and find nothing about it

btw, here's the log
```
currentMouseOver = MutableBlockPos{x=44, y=-29, z=-1356}
[15:46:38] [Render thread/INFO]: [System] [CHAT] [Baritone] Favoring size: 0
[15:46:38] [Render thread/INFO]: [System] [CHAT] [Baritone] Simplifying class baritone.api.pathing.goals.GoalBlock to GoalXZ due to distance
22 movements considered
Open set size: 0
PathNode map size: 1
2147483647 nodes per second
currentMouseOver = MutableBlockPos{x=44, y=-29, z=-1356}
[15:46:38] [Render thread/INFO]: [System] [CHAT] [Baritone] Starting to search for path from BetterBlockPos{x=44,y=-26,z=-1376} to GoalBlock{x=44,y=-29,z=-1356}
[15:46:38] [Render thread/INFO]: [System] [CHAT] [Baritone] Even with a cost coefficient of 10.0, I couldn't get more than 0.0 blocks
[15:46:38] [Render thread/INFO]: [System] [CHAT] [Baritone] No path found =(
currentMouseOver = MutableBlockPos{x=44, y=-29, z=-1356}
```

## Final checklist
- [v] I know how to properly use check boxes 
- [v] I have not used any OwO's or UwU's in this issue.
- [v] I'm so confused rn

**Comment by ZacSharp** [comment]
It's an internal variable controlling the tradeoff between greedily choosing a path reaching close to the goal and choosing a short path when path calculation couldn't get all the way to the goal in time.
However I do not think it is in any way relevant to your problem. In your case the path search expanded exactly one node and didn't reach any position other than the starting position. Since I doubt you'd be here if there actually was no path I suspect you have other mods installed which break Baritone (e.g. farsight, immersive portals, c2me)

**Comment by XiaoGanCN** [comment]
Thanks for helping! I deleted farsight and problem solved
