### ISSUE TITLE
Suggestion: @Getter @Setter

### ISSUE THREAD

**Issue by Baitinq** [cabaletta/baritone#462]
You could really save lots of lines using @Getters and @Setters improving the overall project redeability.

:) maybe ill do a pull request if u lazy to do dat

**Comment by babbaj** [comment]
cringe

**Comment by Baitinq** [comment]
@babbaj no u

**Comment by ZeroMemes** [comment]
I agree that this is cringe. This creates source/compiled inconsistencies and complicates the actual build process, while making code less-explicit.

**Comment by leijurv** [comment]
yep. anything that depends on baritone would then also need to have lombok to have the source match what they're compiling against (as i understand it)

**Comment by Baitinq** [comment]
That's also true

**Comment by fulcanelly** [comment]
WHAAAT

I knew you stupid(baritone community) but that level of stupidness blows my mind...

Do you even know how lombok works ?
It don't add any runtime dependencies 
And if you want clean source without it, you can easily generate them by simple gradle delombok task...

**Comment by fulcanelly** [comment]
> yep. anything that depends on baritone would then also need to have lombok to have the source match what they're compiling against (as i understand it)

WHAAAT

I knew you stupid(baritone community) but that level of stupidness blows my mind...

Do you even know how lombok works ?
It don't add any runtime dependencies
And if you want clean source without it, you can easily generate them by simple gradle delombok task...

**Comment by leijurv** [comment]
@fulcanelly 

I think what I said

> anything that depends on baritone would then also need to have lombok to have the source match what they're compiling against

is correct.

You appear to be skipping the second part of the sentence "to have the source match what they're compiling against". If you're looking at baritone source code (pre-lombok), it would be very different from what you're compiling against (post-lombok)

I believe you may have just chopped off the first half of the sentence "anything that depends on baritone would then also need to have lombok" and declared that to be incorrect.

This would be confusing since then, any project that depends on baritone would be referring to baritone source code with all of lombok's annotations, but in order to use it at runtime they would have to be familiar with how these annotations generate new behaviors at runtime.

**Comment by 0-x-2-2** [comment]
> I knew you stupid(baritone community) but that level of stupidness blows my mind...

https://github.com/fulcanelly/mc-lbalancer/blob/0ff13d33d463ab27754778ed0a8ec4860feaa9f4/src.java/bungee/src/main/java/me/fulcanelly/lbalance/Server.java#L151
