### ISSUE TITLE
building without impact

### ISSUE THREAD

**Issue by yikes4tool** [cabaletta/baritone#560]
how can i build it without impact i didnt understand anything at (master.(

**Comment by StijnSimons** [comment]
Maybe follow the issue template so we get like the slightest bit of information???????????????

**Comment by LoganDark** [comment]
@StijnSimons The issue template is literally "what do you need help with" and "I have not used any OwOs or UwUs"

**Comment by yikes4tool** [comment]
i downloaded file (clone download) and installed gradlew what will i do now ?

**Comment by LoganDark** [comment]
@yikes4tool If you don't know what to do, you shouldn't be building Baritone. Check releases.

**Comment by leijurv** [comment]
this. if you don't know the process for building with gradle and can't follow the instructions in SETUP, then you really should download a prebuilt release (or use impact)

**Comment by yikes4tool** [comment]
Ty

17 Tem 2019 Çar 21:21 tarihinde Leijurv <notifications@github.com> şunu
yazdı:

**Comment by LoganDark** [comment]
To elaborate on that:

Building Baritone for yourself is usually reserved for one of three cases:
- Getting cutting-edge features, like that of the `master` branch or a fork, without a pre-built release.
- Integrating Baritone into a hacked client.
- Hacking on Baritone (adding new features, changing existing ones)

To me, it looks like your use case doesn't fit any of these. But I'll give you a summary of what each one entails.

For the first case, you would use [instructions on how to do this](https://github.com/cabaletta/baritone/blob/master/SETUP.md). It'll generate artifacts, one of which is compatible with Forge. You can then put the Forge artifact, well, into Forge. You would just use the 1.2 versions, since 1.3 is for Minecraft 1.13 and doesn't support Forge yet.

For the second and third cases, you would still review the [instructions](https://github.com/cabaletta/baritone/blob/master/SETUP.md). Those integrating Baritone into a hacked client likely already know their way around Minecraft and Java, and shouldn't need much direction outside of those instructions. Those who want to hack on it will already have everything set up.

Now, back to the fact that your use case doesn't look like any of those... I don't see any compelling features that require you to build a new version for yourself, so the first case isn't what you're looking for, and I don't see any evidence that you're a hacker/programmer, so you won't be able to pull off the second or third ones.

You **should** either download Impact, a hacked client with Baritone integrated already, or download a Forge version (1.2.7 is currently the latest release that has one).

For convenience, the latest Forge version is located [here](https://github.com/cabaletta/baritone/releases/download/v1.2.7/baritone-api-forge-1.2.7.jar). This is for Minecraft 1.12.2. The newer versions are for 1.13, and don't support Forge yet.

Impact can be found [here](https://impactdevelopment.github.io). It includes a lot of other things besides Baritone. If you want to replicate some hacked client functionality in Forge for whatever reason, use [ForgeHax](https://github.com/fr1kin/ForgeHax).

Reply back if you have any questions.

**Comment by xnevis** [comment]
Is there anyway to use baritone on the most recent version of minecraft (1.14.4), because the title states that its should work, however impact does not support that yet.

**Comment by LoganDark** [comment]
@xnevis https://www.youtube.com/watch?v=3ggBfaCE_tk
