### ISSUE TITLE
Baritone auto mine feature does not work

### ISSUE THREAD

**Issue by Egco2811** [cabaletta/baritone#651]
## Some information
Operating system: Windows 10 Pro
Minecraft version: 1.14.4
Baritone version: Most recent on 07/25/2019

## Exception, error or logs
When I start auto mine with or without legit mine enabled the path keeps constantly changing when the bot is near diamonds. The path works fine until like 5 blocks are left between the bot and the diamonds, after that the path suddenly changes and the bot starts to move to the new path without mining the diamonds in the previous destination.

## How to reproduce
Open baritone and type #mine diamond_ore

**Comment by Grovre** [comment]
as long as it doesn't blacklist the blocks because they are presumably unreachable (which isn't the case most of the time), the auto mine will turn around to go back for the ore. Similar to farming or mining any other other, if it doesn't pick up the item it mined then it will go and do that after mining the next few blocks.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Egco2811** [comment]
The bot never mines those blocks. I tried running the bot for like 4 hours and still nothing. Lost 3 pickaxes and no diamonds were mined.

**Comment by atSix** [comment]
If you run the bot on a server it may have anti-xray protection that changes all unexposed stone blocks into ores and then changes it to stone back once they are exposed. So the bot thinks that diamonds are everywhere around him.

**Comment by dominikaaaa** [comment]
If you can still reproduce this issue, please reopen it.
