### ISSUE TITLE
Please add a brief but descriptive title

### ISSUE THREAD

**Issue by LonerStars** [cabaletta/baritone#696]
## Describe your suggestion
An auto strip mine, or at least tunnel, 
so I could do #mine tunnel 2x2 and it would act like #tunnel but do it by those dimensions

## Settings
make it so we can control the dimensions and also auto torch if the light level goes below a certain threshold

## Context
auto torch would be nice because it would 1. stop mobs spawning 2. allow it to be less shady as if i was xraying.

## Final checklist
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by StijnSimons** [comment]
A title would be helpful.

**Comment by SylveonBottle** [comment]
I always thought legitmine was just strip mining forward until it passes by a cave system or ore. Only mine ores visible from the player's perspective (or at least within 10 blocks distance of the stripmine, as long as it doesn't require breaking other blocks to get to it).
+1 though, would be super awesome for some multiplayer servers and scenarios where there's no open ores in a cave system. It should just mine in a straight line (occasionally going back and making multiple stripmines near where it started?) in "search" for ores, instead of just taking whatever weird routes through caves to just get the ores near air blocks.

**Comment by Graicc** [comment]
#740 Seems to be what you are looking for.

**Comment by S-B99** [comment]
This now exists.

**Comment by S-B99** [comment]
Auto torch is  #971 and those tunneling features are now added.
