### ISSUE TITLE
assumeStep liquid issue

### ISSUE THREAD

**Issue by a6d6061ed1** [cabaletta/baritone#727]
## Some information
Operating system: Win10 Pro x64
Java version: 8, Update 221
Minecraft version: 1.12.2
Baritone version: standalone forge 1.2.8
Forge mods (if used): jei, itemzoom, chatflow, journeymap, lunatriuscore, mousetweaks, norecipebook, schematica, shulkerboxviewer, wdlforge, worldedit

## Exception, error or logs
n/a

## How to reproduce

1. Enable `assumeStep` and `assumeWalkOnLava` option
2. Stand in lava (water probably works too) next to block like so:
![javaw_dIrLtNFJpv](https://user-images.githubusercontent.com/20779962/62421386-23e96900-b6a1-11e9-8aa5-89866ba595ea.png)
4. Make baritone go over it somehow (this happens often in normal gameplay)

What will happen is that baritone will think that it can step over block while standing on liquid and since this is impossible (in all scenarios I guess), it'll get stuck forever and try to recalculate the same path until you stop baritone

## Final checklist
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by leijurv** [comment]
Sorry, this is fundamental to how these settings operate.

1. assumeWalkOnWater / assumeWalkOnLava tell Baritone that it should treat those liquids as solid. That it can walk on top of them just like any other block. The responsibility is on some other mod to provide this functionality typically through Jesus.
2. assumeStep tells Baritone that it should not hit space while walking up into a block, since another mod will make it ascend the block.

If your step and your jesus aren't compatible with each other, then that isn't baritone's fault =P
