### ISSUE TITLE
How to create a backport baritone 1.14.4 --> 1.14.2?

### ISSUE THREAD

**Issue by zune127** [cabaletta/baritone#743]
I am a newb at coding, but I can at least try as it shouldn't be that difficult compared to major version ports.  I could try to do it myself, I just need to know where to start. 

edit: didnt wanna repost after i read issues and understand now you're not likely to do a 1.14.2 port

**Comment by LeafHacker** [comment]
Should just be a case of updating the `build.gradle`, since there's already a 1.14.2 vanilla artifact on the [maven](https://github.com/ImpactDevelopment/maven/tree/master/com/github/ImpactDevelopment/Vanilla/1.14.2). In particular [line 141](https://github.com/cabaletta/baritone/blob/4c8907c62999d8c5654b3052a748943c432e5827/build.gradle#L141). I wouldn't expect anything to break baritone between 1.14.2 and 1.14.4 but it's possible.

**Comment by StijnSimons** [comment]
There have been countless issues regarding backports. There wont be one.
