### ISSUE TITLE
just some sugestions

### ISSUE THREAD

**Issue by jdroo** [cabaletta/baritone#884]
Just some Ideas for functions to add, and other random ideas gathered from use.

auto pickup - option allows baritone to wait and then collect any items on the group, this option will remain on unless toggled off, as an example, say you and a friend are cutting trees in sky-block, and one person stays on the ground to collect any saplings that may drop, you could toggle baritone to do this.

Allow baritone to utilize creative flight. some servers give creative flight in survival as a perk for a rank, in example skyblock.net, if there was simply an option to toggle that tells baritone it can fly. [not even sure if this is possible]

## Final checklist
- [ o3o you forgot one ] I have not used any OwO's or UwU's in this issue.

**Comment by LoganDark** [comment]
Auto pickup - MineProcess already does this for any items dropped by the blocks you're mining.

Creative flight - Baritone explicitly disables creative flight because the pathfinding algorithm is not ready for it yet.

If you'd like to communicate with me over Discord about it, I'd be more than glad to see if I can prototype flight. Cuteness#4357

**Comment by S-B99** [comment]
Closed as resolved, also see the features/usage for flight.
