### ISSUE TITLE
When will building in 1.14 be up and ready/why does it crash in the first place?

### ISSUE THREAD

**Issue by NatjoOfficial** [cabaletta/baritone#915]
I'm personally just curious to find out more about the building bug and if there are any plans to solve it. This is a seriously cool bot, even if it can be used for cheats so I find it ashame the most creative aspect of it has been disabled for an entire update and a half.

**Comment by dudeamax99** [comment]
Building does not work in 1.13+ because Mojang removed item id's and now uses name id's.

**Comment by derBobo** [comment]
you can use the 1.14.4 branch if you want to use baritone in mc 1.14.4

**Comment by RGonzalezTechTips** [comment]
If you want this to work in 1.14.4, you can update the code in Schematic.java (/src/main/java/baritone/utils/schematic/Schematic.java)

Schematic files created before 1.13 (generated with Schematica mod) store the block data using numbers. Schematic files created after (generated with Litematica mod) store the data using the block name id.

In theory, you could re-use the code that is currently commented out to read files created before 1.13

However, to support files created afterwards, you'll need to code it to read Litematica (name id) rather than Schematica files (block id [integer]).

Another option: Create a built-in schematic engine/generator to work in 1.14 rather than integrate with Litematica.

Goodluck :P

**Comment by FTC55** [comment]
done ;) My pull request is currently waiting for approval.
