### ISSUE TITLE
blocksToAvoid isn't working

### ISSUE THREAD

**Issue by Nexoloft** [cabaletta/baritone#919]
## Some information
Operating system: Windows 10
Minecraft version: 1.13.2
Impact version: 4.7.3

I put blocks that I want to be avoided in blocksToAvoid, but it doesn't seem to be pathing around the blocks. If I'm doing something wrong, please let me know. I also turned on avoidance. There is also a clear stone path that could've been pathed, but instead it walked over the slime and mycelium which I put to avoid.

https://i.gyazo.com/2c2259c015c6109facc0580aa3693d58.mp4

**Comment by Nexoloft** [comment]
This same thing also happened when I was using 1.13.2 and still version 4.7.3.

**Comment by jonnyawsom3** [comment]
avoidance is for mobs and spawners, and blocksToAvoid are the blocks to avoid mining/breaking

in fact, having avoidance on for the test you did is the reason why it didn't go in a straight line, it was going for the path with the least amount of zombies nearby

**Comment by Credit-Score** [comment]
Agreed, still happening now. Simply seems to ignore the blocks to avoid

**Comment by ZacSharp** [comment]
`blocksToAvoid` prevents Baritone from walking *through* the block, it can still walk on it if it's a full block. Not sure whether this is a bug in the implementation or an error in the javadoc.
It did not take the stone path because you turned `avoidance` on, which increases the cost of walking near mobs by `mobAvoidanceCoefficient` times (defaults to 1.5x) and that seems to be more than walking on slime.
