### ISSUE TITLE
Legit Mine - Unable to find path

### ISSUE THREAD

**Issue by j13li78** [cabaletta/baritone#999]
## Some information
Operating system: Windows 10 Version 1903
Java version: 1.8.0_191
Minecraft version: 1.12.2
Baritone version: 1.2.8
Forge mods (if used): None

## Exception, error or logs
https://gyazo.com/781b5f13247362e358cf6ac387677ebd
[latest.log](https://github.com/cabaletta/baritone/files/3665712/latest.log)

## How to reproduce
I don't know any way to reproduce the issue. It happens randomly that the bot says "Unable to find any path to ORE_BLOCKS, blacklisting presumably unreachable closest instance...", but since I have legit mine enabled this shouldn't happen at all because there is no ORE_BLOCK in his view.

## Final checklist
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by j13li78** [comment]
So i updated to 1.2.9 to make sure if it has been fixed and still came across the exact same issue.
https://gyazo.com/b836cafd402160de772a400531f57c10

**Comment by leijurv** [comment]
`modified` settings?

**Comment by j13li78** [comment]
Only thing that I have modfied.
![Runtime Screenshot 2019 09 28 - 19 11 02 57](https://user-images.githubusercontent.com/40141174/65819978-c4808300-e223-11e9-984e-121c1d4d0065.png)

**Comment by S-B99** [comment]
It can't find any path because there isn't any of that ore.

**Comment by guh0jason** [comment]
You closed this but having no ores isnt the problem im having the same issue and i placed myself the blocks to be sure of it

**Comment by woodendoors7** [comment]
I am having the same problem. 

I am using baritone to #mine birch_leaves with all default settings. There are birch leaves all around me, I am surrounded by them, but it spends tens of seconds trying to find a suitable place to mine, saying `Unable to find any path to BlockOptionalMetaLookup{[BlockOptionalMeta{block=Block{minecraft:birch_leaves}}]}, blacklisting presumably unreachable closest distance.` It spams this same message around every 5 seconds.

Sometimes it spends minutes doing this, with a huge ton of blue paths flashing pointing to (and cancelling) all leaves in render distance, and then just randomly decides to mine a row of birch leaves above me, at which point it does the same thing again. 

At first I thought this could be chunks that are rendered but not loaded (saw someone in a reddit thread mention it) so I made sure to put my render distance very low, but it starts doing this right away after mining a row of leaves, without loading any other chunks than it already has. I made sure to disableCache and actually delete the cache in case it was pulling stuff from the cache, but it wasn't. 

I fixed this by going reasonably far from that place, with the same birch trees. It mined the leaves well, and then it started acting up again after just a few minutes. No idea why this happens somewhere, but doesn't happen somewhere else. 

I know this is closed, but I feel like it was closed unfairly since this is a bug with baritone and "there isn't any of that ore" is incorrect.

**Comment by Amnessie** [comment]
> I am having the same problem.
> 
> I am using baritone to #mine birch_leaves with all default settings. There are birch leaves all around me, I am surrounded by them, but it spends tens of seconds trying to find a suitable place to mine, saying `Unable to find any path to BlockOptionalMetaLookup{[BlockOptionalMeta{block=Block{minecraft:birch_leaves}}]}, blacklisting presumably unreachable closest distance.` It spams this same message around every 5 seconds.
> 
> Sometimes it spends minutes doing this, with a huge ton of blue paths flashing pointing to (and cancelling) all leaves in render distance, and then just randomly decides to mine a row of birch leaves above me, at which point it does the same thing again.
> 
> At first I thought this could be chunks that are rendered but not loaded (saw someone in a reddit thread mention it) so I made sure to put my render distance very low, but it starts doing this right away after mining a row of leaves, without loading any other chunks than it already has. I made sure to disableCache and actually delete the cache in case it was pulling stuff from the cache, but it wasn't.
> 
> I fixed this by going reasonably far from that place, with the same birch trees. It mined the leaves well, and then it started acting up again after just a few minutes. No idea why this happens somewhere, but doesn't happen somewhere else.
> 
> I know this is closed, but I feel like it was closed unfairly since this is a bug with baritone and "there isn't any of that ore" is incorrect.

yes same thing happens to me with dark_oak_leaves 

did you found any fix for this? I'm working on a large project

**Comment by woodendoors7** [comment]
@Amnessie yup, no fix. And it doesn't look like they're planning to fix it anytime soon either. It's been happening ever since, nothing's changed.
